"""
Regenerates all 6 EM Risk Dashboard notebooks:
  00_master.ipynb, 01_data_validation.ipynb, 02_turbulence_audit.ipynb,
  03_factor_structure.ipynb, 04_regime_analysis.ipynb, 05_methodology_sandbox.ipynb
"""

import json, pathlib, uuid

NB_DIR = pathlib.Path("notebooks")
NB_DIR.mkdir(exist_ok=True)


# ── helpers ──────────────────────────────────────────────────────────────────

def new_id():
    return uuid.uuid4().hex[:8]

def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12.0"},
        },
        "cells": cells,
    }

def md(*lines):
    return {"id": new_id(), "cell_type": "markdown", "metadata": {},
            "source": [l + "\n" for l in lines]}

def code(*lines):
    return {"id": new_id(), "cell_type": "code", "execution_count": None,
            "metadata": {}, "outputs": [],
            "source": [l + "\n" for l in lines]}

def save(name, cells):
    path = NB_DIR / name
    with open(path, "w") as f:
        json.dump(nb(cells), f, indent=1)
    print(f"  wrote {path}")


# ── shared widget block (used in NB02, 03, 04) ───────────────────────────────

WIDGET_CELL = code(
    "import ipywidgets as widgets",
    "from IPython.display import display",
    "",
    "w_start  = widgets.DatePicker(description='Start date',",
    "               value=__import__('datetime').date(2015, 1, 1))",
    "w_end    = widgets.DatePicker(description='End date',",
    "               value=__import__('datetime').date(2024, 12, 31))",
    "w_window = widgets.IntSlider(min=63, max=504, step=21, value=252,",
    "               description='Window', style={'description_width':'initial'})",
    "w_slow_w = widgets.IntSlider(min=126, max=756, step=63, value=504,",
    "               description='Slow window', style={'description_width':'initial'})",
    "w_lam    = widgets.FloatSlider(min=0.90, max=0.99, step=0.01, value=0.94,",
    "               description='EWMA lambda', style={'description_width':'initial'},",
    "               readout_format='.2f')",
    "w_vs     = widgets.Checkbox(value=True, description='Vol-standardize turbulence')",
    "",
    "display(widgets.VBox([",
    "    widgets.HBox([w_start, w_end]),",
    "    w_window, w_slow_w, w_lam, w_vs,",
    "]))",
    "print('Adjust parameters above, then run the next cell.')",
)

READ_PARAMS_CELL = code(
    "# Read current widget values — run this after adjusting sliders",
    "START   = str(w_start.value)",
    "END     = str(w_end.value)",
    "WINDOW  = w_window.value",
    "SLOW_W  = w_slow_w.value",
    "LAM     = w_lam.value",
    "VOL_STD = w_vs.value",
    "",
    "print(f'Parameters: start={START}  end={END}  window={WINDOW}')",
    "print(f'            slow_w={SLOW_W}  lam={LAM:.2f}  vol_std={VOL_STD}')",
)


# ══════════════════════════════════════════════════════════════════════════════
# 00_master.ipynb — daily monitoring, reads from cache, <10s per run
# ══════════════════════════════════════════════════════════════════════════════
save("00_master.ipynb", [

md("# 00 · Master Daily Monitor",
   "**Daily entry point.** Loads pre-computed metrics from disk cache.",
   "No heavy recomputation — cold run <10 s, warm run <1 s.",
   "Edit parameters in Cell 1, run all (Kernel → Restart & Run All)."),

code(
    "import sys, os, hashlib",
    "sys.path.insert(0, os.path.join(os.getcwd(), '..'))",
    "import warnings; warnings.filterwarnings('ignore')",
    "import numpy as np",
    "import pandas as pd",
    "import plotly.graph_objects as go",
    "from plotly.subplots import make_subplots",
    "import matplotlib.pyplot as plt",
    "from IPython.display import display",
    "",
    "# ── Edit parameters here ─────────────────────────────────────────────",
    "WINDOW  = 252",
    "LAM     = 0.94",
    "VOL_STD = True",
    "SLOW_W  = 504",
    "START   = '2015-01-01'",
    "# ─────────────────────────────────────────────────────────────────────",
    "print('Setup complete.')",
),

md("## Cell 2 — Load Data & Metrics"),

code(
    "from data.metric_store import MetricStore",
    "from core.metric_cache import (",
    "    make_key, exists,",
    "    save_turbulence, load_turbulence,",
    "    save_absorption, load_absorption,",
    "    save_dynamic,    load_dynamic,",
    ")",
    "from modules.turbulence import compute_turbulence_index",
    "from modules.absorption import compute_absorption_ratio",
    "from modules.pca_kalman import compute_dynamic_factors_v2",
    "",
    "# --- load raw data (live → synthetic fallback) ----------------------",
    "DATA_SOURCE = 'Synthetic'",
    "try:",
    "    from data.fetcher import load_em_universe",
    "    from core.returns import log_returns",
    "    raw        = load_em_universe(start=START, use_cache=True)",
    "    fx_ret     = log_returns(raw['fx'])",
    "    eq_ret     = log_returns(raw['equity'])",
    "    global_ret = log_returns(raw['global'])",
    "    panel      = pd.concat([fx_ret, eq_ret, global_ret], axis=1).dropna(how='all')",
    "    DATA_SOURCE = 'Live'",
    "except Exception as _e:",
    "    from data.synthetic import generate_em_universe",
    "    from core.returns import log_returns",
    "    _uni       = generate_em_universe(seed=42, start=START)",
    "    fx_ret     = _uni.fx",
    "    eq_ret     = _uni.equity",
    "    panel      = _uni.panel",
    "",
    "data_key    = hashlib.md5(str(pd.util.hash_pandas_object(panel, index=True).sum()).encode()).hexdigest()[:16]",
    "params_turb = f'w{WINDOW}_vs{int(VOL_STD)}'",
    "params_frag = f'w{WINDOW}_lam{int(round(LAM*100))}'",
    "store       = MetricStore('../data/_cache/metrics.db')",
    "",
    "# --- load or compute turbulence panel --------------------------------",
    "k_turb_panel = make_key('turb_panel', data_key, WINDOW, int(VOL_STD))",
    "if exists(k_turb_panel):",
    "    turb_panel = load_turbulence(k_turb_panel)",
    "else:",
    "    kw = dict(window=WINDOW, min_periods=60, vol_standardize=VOL_STD, slow_window=SLOW_W)",
    "    _tp = compute_turbulence_index(panel, **kw)",
    "    save_turbulence(k_turb_panel, _tp)",
    "    turb_panel = load_turbulence(k_turb_panel)",
    "",
    "# --- load or compute absorption ratio --------------------------------",
    "k_ar = make_key('ar', data_key, WINDOW, int(round(LAM*100)))",
    "if exists(k_ar):",
    "    ar_result = load_absorption(k_ar)",
    "else:",
    "    _ar = compute_absorption_ratio(fx_ret, window=WINDOW, min_periods=60, lam=LAM)",
    "    save_absorption(k_ar, _ar)",
    "    ar_result = load_absorption(k_ar)",
    "",
    "# --- load or compute dynamic factors ---------------------------------",
    "k_dyn = make_key('dyn', data_key, WINDOW, int(round(LAM*100)))",
    "if exists(k_dyn):",
    "    dyn_result = load_dynamic(k_dyn)",
    "else:",
    "    _dyn = compute_dynamic_factors_v2(panel, window=WINDOW, n_components=3, min_periods=60, lam=LAM)",
    "    save_dynamic(k_dyn, _dyn)",
    "    dyn_result = load_dynamic(k_dyn)",
    "",
    "# --- load or compute per-country turbulence --------------------------",
    "fx_cols = list(fx_ret.columns)",
    "eq_cols = list(eq_ret.columns)",
    "country_turb = {}",
    "for i, col in enumerate(fx_cols):",
    "    k_ct = make_key('turb', col, data_key, WINDOW, int(VOL_STD))",
    "    if exists(k_ct):",
    "        country_turb[col] = load_turbulence(k_ct)",
    "    else:",
    "        kw = dict(window=WINDOW, min_periods=60, vol_standardize=VOL_STD, slow_window=SLOW_W)",
    "        _ct = compute_turbulence_index(pd.concat([fx_ret[[col]], eq_ret[[eq_cols[i]]]], axis=1), **kw)",
    "        save_turbulence(k_ct, _ct)",
    "        country_turb[col] = load_turbulence(k_ct)",
    "",
    "last_date = turb_panel.turbulence.dropna().index[-1]",
    "print(f'Source    : {DATA_SOURCE}')",
    "print(f'Panel     : {panel.shape}')",
    "print(f'Last date : {last_date.date()}')",
    "print(f'Regime    : {turb_panel.current_regime()}')",
),

md("## Cell 3 — Current Regime Summary"),

code(
    "from scipy import stats as sp_stats",
    "",
    "def _pctile(series):",
    "    s = series.dropna()",
    "    return float(sp_stats.percentileofscore(s.values, float(s.iloc[-1])))",
    "",
    "def _signal(pctile):",
    "    if pctile > 90: return 'CRISIS'",
    "    if pctile > 75: return 'ELEVATED'",
    "    return 'NORMAL'",
    "",
    "ar_pct = _pctile(ar_result.absorption_ratio)",
    "inorm  = dyn_result.pca.innovation_norm.dropna()",
    "inorm_pct = float(sp_stats.percentileofscore(inorm.values, float(inorm.iloc[-1])))",
    "",
    "rows = [",
    "    {'Metric':'Panel Turbulence tau',",
    "     'Value': round(turb_panel.current_score(),2),",
    "     'Percentile': round(turb_panel.current_pctile(),1),",
    "     'Regime': turb_panel.current_regime(),",
    "     'Signal': _signal(turb_panel.current_pctile())},",
    "    {'Metric':'Absorption Ratio AR',",
    "     'Value': round(float(ar_result.absorption_ratio.dropna().iloc[-1]),4),",
    "     'Percentile': round(ar_pct,1),",
    "     'Regime': _signal(ar_pct), 'Signal': _signal(ar_pct)},",
    "    {'Metric':'Innovation Norm ||dR||_F',",
    "     'Value': round(float(inorm.iloc[-1]),4),",
    "     'Percentile': round(inorm_pct,1),",
    "     'Regime': _signal(inorm_pct), 'Signal': _signal(inorm_pct)},",
    "]",
    "for col in fx_cols:",
    "    ct = country_turb[col]",
    "    pct = ct.current_pctile()",
    "    rows.append({'Metric': f'{col} Turbulence tau',",
    "                 'Value': round(ct.current_score(),2),",
    "                 'Percentile': round(pct,1),",
    "                 'Regime': ct.current_regime(),",
    "                 'Signal': _signal(pct)})",
    "",
    "df_summary = pd.DataFrame(rows).set_index('Metric')",
    "",
    "def _color(val):",
    "    if val == 'CRISIS':   return 'background-color:#3a0a0a;color:#e74c3c'",
    "    if val == 'ELEVATED': return 'background-color:#3a2e0a;color:#f39c12'",
    "    return 'background-color:#1a3a2a;color:#2ecc71'",
    "",
    "print(f'As of {last_date.date()}: Overall regime = {turb_panel.current_regime()}')",
    "print()",
    "print(df_summary.to_string())",
),

md("## Cell 4 — Recent Turbulence Chart (last 252 trading days)"),

code(
    "REGIME_HEX = {'Calm':'#2ecc71','Elevated':'#f39c12','Turbulent':'#e67e22','Crisis':'#e74c3c'}",
    "",
    "ts  = turb_panel.turbulence.dropna().iloc[-252:]",
    "reg = turb_panel.regime.reindex(ts.index)",
    "",
    "fig = go.Figure()",
    "in_block, x0, prev_r = False, None, None",
    "for dt, r in reg.items():",
    "    if r != prev_r:",
    "        if in_block and prev_r in REGIME_HEX:",
    "            fig.add_vrect(x0=x0, x1=dt, fillcolor=REGIME_HEX[prev_r], opacity=0.15, line_width=0)",
    "        x0, in_block = dt, True",
    "    prev_r = r",
    "if in_block and prev_r in REGIME_HEX:",
    "    fig.add_vrect(x0=x0, x1=ts.index[-1], fillcolor=REGIME_HEX[prev_r], opacity=0.15, line_width=0)",
    "",
    "fig.add_trace(go.Scatter(x=ts.index, y=ts.values, mode='lines',",
    "    name='tau', line=dict(color='#00d4aa', width=1.3),",
    "    fill='tozeroy', fillcolor='rgba(0,212,170,0.06)'))",
    "for thr, lbl in [('elevated','Elevated'),('turbulent','Turbulent'),('crisis','Crisis')]:",
    "    fig.add_hline(y=turb_panel.thresholds[thr], line_dash='dash',",
    "        line_color=REGIME_HEX[lbl], line_width=0.8)",
    "fig.update_layout(template='plotly_dark', height=320,",
    "    title=f'Turbulence Index — {last_date.date()}  Regime: {turb_panel.current_regime()}',",
    "    margin=dict(l=40,r=40,t=40,b=40),",
    "    yaxis=dict(title='tau (Mahalanobis2, vol-std)'),",
    "    xaxis=dict(showgrid=False),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig.show()",
),

md("## Cell 5 — Absorption Ratio & Innovation Norm (last 252 days)"),

code(
    "ar_ts    = ar_result.absorption_ratio.dropna().iloc[-252:]",
    "ar_ma63  = ar_ts.rolling(63, min_periods=20).mean()",
    "inorm_ts = dyn_result.pca.innovation_norm.dropna().iloc[-252:]",
    "inorm_thr = float(inorm_ts.mean()) + 2.0 * float(inorm_ts.std())",
    "",
    "fig2 = make_subplots(rows=2, cols=1, shared_xaxes=True,",
    "    row_heights=[0.6, 0.4], vertical_spacing=0.05)",
    "fig2.add_trace(go.Scatter(x=ar_ts.index, y=ar_ts.values, mode='lines',",
    "    name='AR', line=dict(color='#e67e22', width=1.3),",
    "    fill='tozeroy', fillcolor='rgba(230,126,34,0.08)'), row=1, col=1)",
    "fig2.add_trace(go.Scatter(x=ar_ma63.index, y=ar_ma63.values, mode='lines',",
    "    name='AR 63d MA', line=dict(color='#f39c12', width=1.2, dash='dot')), row=1, col=1)",
    "fig2.add_trace(go.Scatter(x=inorm_ts.index, y=inorm_ts.values, mode='lines',",
    "    name='||dR||_F', line=dict(color='#e74c3c', width=1.0),",
    "    fill='tozeroy', fillcolor='rgba(231,76,60,0.07)'), row=2, col=1)",
    "fig2.add_hline(y=inorm_thr, line_dash='dash', line_color='#f39c12',",
    "    line_width=1.0, row=2, col=1)",
    "fig2.update_layout(template='plotly_dark', height=380,",
    "    title='Spectral Fragility: AR + Innovation Norm',",
    "    margin=dict(l=40,r=40,t=40,b=40),",
    "    yaxis=dict(title='AR'), yaxis2=dict(title='||dR||_F'),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig2.show()",
),

md("## Cell 6 — Country Scorecard (last 21 trading days)"),

code(
    "rows6 = []",
    "for i, col in enumerate(fx_cols):",
    "    ct   = country_turb[col]",
    "    fx_s = fx_ret[col].dropna()",
    "    eq_s = eq_ret[eq_cols[i]].dropna() if i < len(eq_cols) else pd.Series(dtype=float)",
    "    fx_1w  = float(fx_s.iloc[-5:].sum()  * 100) if len(fx_s) >= 5  else float('nan')",
    "    fx_1m  = float(fx_s.iloc[-21:].sum() * 100) if len(fx_s) >= 21 else float('nan')",
    "    eq_1w  = float(eq_s.iloc[-5:].sum()  * 100) if len(eq_s) >= 5  else float('nan')",
    "    eq_1m  = float(eq_s.iloc[-21:].sum() * 100) if len(eq_s) >= 21 else float('nan')",
    "    rows6.append({",
    "        'Country': col,",
    "        'FX 1W%':  round(fx_1w, 2),",
    "        'FX 1M%':  round(fx_1m, 2),",
    "        'FX tau':  round(ct.current_score(), 2),",
    "        'FX Regime': ct.current_regime(),",
    "        'EQ 1W%':  round(eq_1w, 2),",
    "        'EQ 1M%':  round(eq_1m, 2),",
    "        'Stress pctile': round(ct.current_pctile(), 1),",
    "    })",
    "df_scorecard = pd.DataFrame(rows6).set_index('Country')",
    "print(df_scorecard.to_string())",
),

md("## Cell 7 — Automatic Alerts"),

code(
    "alerts = []",
    "for metric, row in df_summary.iterrows():",
    "    pct = row['Percentile']",
    "    if pct > 90:",
    "        alerts.append(f'CRISIS  {metric}: {row[\"Value\"]} ({pct:.0f}th pctile) — {row[\"Regime\"]}')",
    "    elif pct > 75:",
    "        alerts.append(f'ELEVATED {metric}: {row[\"Value\"]} ({pct:.0f}th pctile)')",
    "",
    "if alerts:",
    "    print('ACTIVE ALERTS:')",
    "    for a in alerts: print(f'  {a}')",
    "else:",
    "    print('All metrics within normal range.')",
),

md("## Cell 8 — Export Snapshot to Excel"),

code(
    "from datetime import date",
    "os.makedirs('../exports', exist_ok=True)",
    "",
    "filename = f'../exports/daily_snapshot_{date.today()}.xlsx'",
    "with pd.ExcelWriter(filename, engine='openpyxl') as writer:",
    "    df_summary.to_excel(writer, sheet_name='Summary')",
    "    turb_panel.to_frame().tail(252).to_excel(writer, sheet_name='Turbulence 1Y')",
    "    ar_result.to_frame().tail(252).to_excel(writer, sheet_name='AR 1Y')",
    "    dyn_result.to_frame().tail(252).to_excel(writer, sheet_name='Factors 1Y')",
    "    for country, ct in country_turb.items():",
    "        ct.to_frame().tail(252).to_excel(writer, sheet_name=f'Turb_{country}')",
    "print(f'Exported: {filename}')",
),

])  # end 00_master


# ══════════════════════════════════════════════════════════════════════════════
# 01_data_validation.ipynb
# ══════════════════════════════════════════════════════════════════════════════
save("01_data_validation.ipynb", [

md("# 01 · Data Validation",
   "Live or synthetic price levels, data quality, correlation regimes."),

code(
    "import sys, os",
    "sys.path.insert(0, os.path.join(os.getcwd(), '..'))",
    "import warnings; warnings.filterwarnings('ignore')",
    "import numpy as np",
    "import pandas as pd",
    "import matplotlib.pyplot as plt",
    "import matplotlib.dates as mdates",
    "import seaborn as sns",
    "",
    "USE_LIVE = False",
    "",
    "if USE_LIVE:",
    "    try:",
    "        from data.fetcher import load_em_universe",
    "        from core.returns import log_returns",
    "        raw = load_em_universe(start='2015-01-01')",
    "        fx_prices = raw['fx']; eq_prices = raw['equity']",
    "        fx_ret = log_returns(fx_prices); eq_ret = log_returns(eq_prices)",
    "        DATA_SOURCE = 'Live'",
    "    except Exception as exc:",
    "        print(f'Live failed ({exc}) — synthetic'); USE_LIVE = False",
    "",
    "if not USE_LIVE:",
    "    from data.synthetic import generate_em_universe",
    "    uni = generate_em_universe(seed=42)",
    "    fx_prices = uni.prices_fx; eq_prices = uni.prices_eq",
    "    fx_ret = uni.fx; eq_ret = uni.equity",
    "    DATA_SOURCE = 'Synthetic'",
    "",
    "print(f'Source : {DATA_SOURCE}')",
    "print(f'FX     : {fx_prices.shape}  {fx_prices.index[0].date()} to {fx_prices.index[-1].date()}')",
),

md("## 2 · Price Levels Table — last 10 rows with range flags"),

code(
    "FX_RANGES  = dict(CLP=(500,1200), BRL=(2.,8.), MXN=(10.,25.), COP=(1500,6000), PEN=(2.5,4.5))",
    "EQ_RANGES  = dict(CHL=(1,500), BRA=(1,500), MEX=(1,500), COL=(1,500), PER=(1,500))",
    "",
    "def range_table(df, ranges):",
    "    rows = []",
    "    for col in df.columns:",
    "        s = df[col].dropna()",
    "        if s.empty: continue",
    "        lo, hi = ranges.get(col, (float('-inf'), float('inf')))",
    "        latest = float(s.iloc[-1])",
    "        rows.append({'Series': col, 'Latest Date': str(s.index[-1].date()),",
    "                     'Latest Price': round(latest,4), 'Low': lo, 'High': hi,",
    "                     'Pass': 'OK' if lo <= latest <= hi else 'FAIL'})",
    "    return pd.DataFrame(rows).set_index('Series')",
    "",
    "print('FX (local CCY per USD):'); print(range_table(fx_prices, FX_RANGES).to_string())",
    "print(); print('Equity ETF (USD):');   print(range_table(eq_prices, EQ_RANGES).to_string())",
    "print(); print('Last 10 FX rows:');    print(fx_prices.tail(10).round(4).to_string())",
),

md("## 3 · Data Quality — NaN counts, gaps, annualized volatility"),

code(
    "def quality_report(returns_df, label):",
    "    rows = []",
    "    for col in returns_df.columns:",
    "        s = returns_df[col]",
    "        valid = s.dropna()",
    "        if len(valid) < 2:",
    "            rows.append({'Series': col, 'NaN%': round(s.isna().mean()*100,2), 'Max gap (d)': 0, 'Ann vol %': float('nan')})",
    "            continue",
    "        run_lens, cur = [], 0",
    "        for v in s.isna():",
    "            if v: cur += 1",
    "            else:",
    "                if cur: run_lens.append(cur)",
    "                cur = 0",
    "        if cur: run_lens.append(cur)",
    "        rows.append({'Series': col, 'NaN%': round(s.isna().mean()*100,2),",
    "                     'Max gap (d)': max(run_lens) if run_lens else 0,",
    "                     'Ann vol %': round(float(valid.std()*np.sqrt(252)*100),1)})",
    "    print(f'--- {label} ---'); print(pd.DataFrame(rows).set_index('Series').to_string())",
    "    return pd.DataFrame(rows).set_index('Series')",
    "",
    "dq_fx = quality_report(fx_ret, 'FX returns')",
    "print(); dq_eq = quality_report(eq_ret, 'Equity returns')",
),

md("## 4 · FX Price Levels (rebased to 100 at start)"),

code(
    "colors = ['#00d4aa','#e74c3c','#f39c12','#9b59b6','#3498db']",
    "fig, ax = plt.subplots(figsize=(12, 4))",
    "for i, col in enumerate(fx_prices.columns):",
    "    s = fx_prices[col].dropna(); rebased = s / s.iloc[0] * 100",
    "    ax.plot(rebased.index, rebased, label=col, color=colors[i], lw=1.3)",
    "    ax.annotate(f'{col} {rebased.iloc[-1]:.1f}', xy=(rebased.index[-1], rebased.iloc[-1]),",
    "                xytext=(5,0), textcoords='offset points', fontsize=8, color=colors[i], va='center')",
    "ax.set_title('EM FX vs USD (rebased to 100)'); ax.set_ylabel('Index')",
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))",
    "ax.legend(loc='upper left', fontsize=9); ax.grid(alpha=0.2)",
    "plt.tight_layout(); plt.show()",
),

md("## 5 · Equity ETF Prices (rebased to 100)"),

code(
    "fig, ax = plt.subplots(figsize=(12, 4))",
    "for i, col in enumerate(eq_prices.columns):",
    "    s = eq_prices[col].dropna(); rebased = s / s.iloc[0] * 100",
    "    ax.plot(rebased.index, rebased, label=col, color=colors[i], lw=1.3)",
    "    ax.annotate(f'{col} {rebased.iloc[-1]:.1f}', xy=(rebased.index[-1], rebased.iloc[-1]),",
    "                xytext=(5,0), textcoords='offset points', fontsize=8, color=colors[i], va='center')",
    "ax.set_title('EM Equity ETFs (rebased to 100)'); ax.set_ylabel('Index')",
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))",
    "ax.legend(loc='upper left', fontsize=9); ax.grid(alpha=0.2)",
    "plt.tight_layout(); plt.show()",
),

md("## 6 · Pairwise Correlation Heatmap — Calm vs Stress"),

code(
    "CALM_S, CALM_E    = '2018-01-01', '2019-12-31'",
    "STRESS_S, STRESS_E = '2020-02-20', '2020-04-30'",
    "",
    "panel_ret   = pd.concat([fx_ret, eq_ret], axis=1).dropna(how='all')",
    "corr_calm   = panel_ret.loc[CALM_S:CALM_E].corr()",
    "corr_stress = panel_ret.loc[STRESS_S:STRESS_E].corr()",
    "corr_delta  = corr_stress - corr_calm",
    "",
    "fig, axes = plt.subplots(1, 3, figsize=(18, 5))",
    "kw = dict(vmin=-1, vmax=1, cmap='RdBu_r', annot=True, fmt='.2f', linewidths=0.3, annot_kws={'size':7})",
    "sns.heatmap(corr_calm,   ax=axes[0], **kw); axes[0].set_title(f'Calm ({CALM_S} to {CALM_E})')",
    "sns.heatmap(corr_stress, ax=axes[1], **kw); axes[1].set_title('Stress (COVID)')",
    "dkw = dict(vmin=-0.6, vmax=0.6, cmap='RdYlGn_r', annot=True, fmt='+.2f', linewidths=0.3, annot_kws={'size':7})",
    "sns.heatmap(corr_delta,  ax=axes[2], **dkw); axes[2].set_title('Delta (Stress minus Calm)')",
    "plt.tight_layout(); plt.show()",
    "mask = ~np.eye(len(corr_calm), dtype=bool)",
    "print(f'Avg off-diag corr  Calm:   {corr_calm.where(mask).stack().mean():.3f}')",
    "print(f'Avg off-diag corr  Stress: {corr_stress.where(mask).stack().mean():.3f}')",
),

md("## 7 · Manual Spot-Check — price vs log-return consistency"),

code(
    "loc = fx_prices.index.get_indexer([pd.Timestamp('2020-03-20')], method='nearest')[0]",
    "audit_date = fx_prices.index[loc]",
    "CHECK_SERIES = fx_prices.columns[0]",
    "stored = float(fx_prices.iloc[loc][CHECK_SERIES])",
    "print(f'Check date: {audit_date.date()}   Series: {CHECK_SERIES}')",
    "print(f'Stored price: {stored:.4f}')",
    "if loc > 0 and CHECK_SERIES in fx_ret.columns and audit_date in fx_ret.index:",
    "    prev  = float(fx_prices.iloc[loc-1][CHECK_SERIES])",
    "    lr    = float(fx_ret.loc[audit_date, CHECK_SERIES])",
    "    recon = prev * np.exp(lr)",
    "    diff  = abs(stored - recon)",
    "    print(f'Reconstructed: {recon:.4f}   Diff: {diff:.6f}')",
    "    print('Consistency: OK' if diff < 0.01 else 'Consistency: DISCREPANCY')",
),

md("## 8 · Export to Excel"),

code(
    "from datetime import date",
    "os.makedirs('../exports', exist_ok=True)",
    "filename = f'../exports/01_data_validation_{date.today()}.xlsx'",
    "with __import__('openpyxl') and pd.ExcelWriter(filename, engine='openpyxl') as writer:",
    "    fx_prices.tail(252).to_excel(writer, sheet_name='FX Prices')",
    "    eq_prices.tail(252).to_excel(writer, sheet_name='Equity Prices')",
    "    dq_fx.to_excel(writer, sheet_name='Data Quality FX')",
    "    dq_eq.to_excel(writer, sheet_name='Data Quality EQ')",
    "    fx_ret.tail(252).to_excel(writer, sheet_name='FX Returns')",
    "    eq_ret.tail(252).to_excel(writer, sheet_name='Equity Returns')",
    "    corr_calm.to_excel(writer, sheet_name='Correlation Calm')",
    "    corr_stress.to_excel(writer, sheet_name='Correlation Stress')",
    "print(f'Exported: {filename}')",
),

])  # end 01


# ══════════════════════════════════════════════════════════════════════════════
# 02_turbulence_audit.ipynb
# ══════════════════════════════════════════════════════════════════════════════
save("02_turbulence_audit.ipynb", [

md("# 02 · Turbulence Audit",
   "Manual tau replication, chi2(N) calibration, decomposition, vol-standardization.",
   "Use the parameter widgets below to change estimation settings without restarting."),

code(
    "import sys, os",
    "sys.path.insert(0, os.path.join(os.getcwd(), '..'))",
    "import warnings; warnings.filterwarnings('ignore')",
    "import numpy as np",
    "import pandas as pd",
    "import matplotlib.pyplot as plt",
    "import matplotlib.dates as mdates",
    "import matplotlib.patches as mpatches",
    "from scipy import stats as sp_stats",
    "from statsmodels.distributions.empirical_distribution import ECDF",
    "from data.synthetic import generate_em_universe",
    "from modules.turbulence import compute_turbulence_index, crisis_episodes",
    "from core.covariance import SlowCovariance, VolStandardizer",
    "print('Imports OK')",
),

md("### Parameters (interactive)"),
WIDGET_CELL,
READ_PARAMS_CELL,

md("### Data & Computation"),

code(
    "uni    = generate_em_universe(seed=42, start=START)",
    "panel  = uni.panel",
    "fx_ret = uni.fx",
    "eq_ret = uni.equity",
    "",
    "kw = dict(window=WINDOW, min_periods=60, vol_standardize=VOL_STD, slow_window=SLOW_W)",
    "turb_vs   = compute_turbulence_index(panel,  **kw)",
    "turb_raw  = compute_turbulence_index(panel,  **{**kw, 'vol_standardize': False})",
    "turb_fx   = compute_turbulence_index(fx_ret, **kw)",
    "turb_eq   = compute_turbulence_index(eq_ret, **kw)",
    "",
    "print(f'Panel shape : {panel.shape}')",
    "print(f'Regime (vol-std): {turb_vs.current_regime()}  score: {turb_vs.current_score():.2f}')",
),

md("## 2 · Manual tau Replication",
   "tau_t = (r_t - mu)' Sigma^{-1} (r_t - mu),  Sigma = SLOW-track covariance."),

code(
    "TARGET = '2020-03-20'",
    "loc = panel.index.get_indexer([TARGET], method='nearest')[0]",
    "audit_idx = panel.index[loc]",
    "print(f'Audit date: {audit_idx.date()}')",
    "",
    "window_data = panel.iloc[max(0, loc-SLOW_W):loc].dropna(how='any')",
    "cov_result  = SlowCovariance().fit(window_data, window=SLOW_W)",
    "mu          = cov_result.mu",
    "Sigma_inv   = cov_result.sigma_inv",
    "",
    "vol_std_panel = VolStandardizer().fit_transform(panel).fillna(0.0)",
    "r_t = vol_std_panel.loc[audit_idx].values if VOL_STD else panel.loc[audit_idx].values",
    "",
    "tau_manual = float((r_t - mu) @ Sigma_inv @ (r_t - mu))",
    "tau_module = float(turb_vs.turbulence.loc[audit_idx])",
    "replication_df = pd.DataFrame([{'Date': str(audit_idx.date()),",
    "    'tau_manual': round(tau_manual,4), 'tau_module': round(tau_module,4),",
    "    'abs_diff': round(abs(tau_manual - tau_module),6)}])",
    "print(replication_df.to_string(index=False))",
    "print(f'Regime: {turb_vs.regime.loc[audit_idx]}')",
),

md("## 3 · chi2(N) Calibration Plot"),

code(
    "N = panel.shape[1]",
    "CALM_MASK = ((panel.index >= '2015-01-01') & (panel.index < '2018-06-01')) | \\",
    "            ((panel.index >= '2021-01-01') & (panel.index < '2022-01-01'))",
    "tau_calm = turb_vs.turbulence.loc[CALM_MASK].dropna()",
    "",
    "x = np.linspace(0, float(tau_calm.quantile(0.999)), 300)",
    "chi2_cdf = sp_stats.chi2.cdf(x, df=N)",
    "emp_cdf  = ECDF(tau_calm.values)(x)",
    "calibration_df = pd.DataFrame({'x': x.round(4), 'empirical_cdf': emp_cdf.round(4),",
    "                                'chi2_cdf': chi2_cdf.round(4)})",
    "",
    "fig, ax = plt.subplots(figsize=(8, 5))",
    "ax.plot(x, chi2_cdf, 'r--', lw=1.5, label=f'Theoretical chi2({N})')",
    "ax.plot(x, emp_cdf,  'b-',  lw=1.5, label='Empirical (calm)')",
    "ax.axvline(sp_stats.chi2.ppf(0.95, N), color='orange', ls=':', alpha=0.7, label='chi2(0.95)')",
    "ax.axvline(sp_stats.chi2.ppf(0.99, N), color='red',    ls=':', alpha=0.7, label='chi2(0.99)')",
    "ax.set_xlabel('tau'); ax.set_ylabel('CDF')",
    "ax.set_title(f'Empirical vs chi2({N}) CDF — calm-period tau')",
    "ax.legend(); ax.grid(alpha=0.2)",
    "plt.tight_layout(); plt.show()",
    "print(f'Calm tau mean={tau_calm.mean():.2f}  chi2({N}) mean={N}')",
),

md("## 4 · Turbulence Time Series with Regime Shading"),

code(
    "REGIME_HEX = {'Calm':'#2ecc71','Elevated':'#f39c12','Turbulent':'#e67e22','Crisis':'#e74c3c'}",
    "fig, ax = plt.subplots(figsize=(14, 4))",
    "ts  = turb_vs.turbulence.dropna()",
    "reg = turb_vs.regime.reindex(ts.index)",
    "for label, col in REGIME_HEX.items():",
    "    mask = reg == label",
    "    if not mask.any(): continue",
    "    in_block, x0 = False, None",
    "    for dt, val in mask.items():",
    "        if val and not in_block:  x0, in_block = dt, True",
    "        elif not val and in_block: ax.axvspan(x0, dt, alpha=0.25, color=col, lw=0); in_block = False",
    "    if in_block: ax.axvspan(x0, mask.index[-1], alpha=0.25, color=col, lw=0)",
    "ax.plot(ts.index, ts.values, color='#00d4aa', lw=0.9)",
    "for thr, label in [('elevated','Elevated'),('turbulent','Turbulent'),('crisis','Crisis')]:",
    "    ax.axhline(turb_vs.thresholds[thr], color=REGIME_HEX[label], ls='--', lw=0.8, alpha=0.7)",
    "patches = [mpatches.Patch(color=REGIME_HEX[l], alpha=0.5, label=l) for l in REGIME_HEX]",
    "ax.legend(handles=patches, loc='upper left', fontsize=8)",
    "ax.set_ylabel('tau (vol-std)'); ax.grid(alpha=0.15)",
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))",
    "ax.set_title(f'Turbulence Index (window={WINDOW}, slow_w={SLOW_W})')",
    "plt.tight_layout(); plt.show()",
),

md("## 5 · Magnitude vs Correlation Decomposition"),

code(
    "fig, axes = plt.subplots(2, 1, figsize=(14, 6), sharex=True)",
    "mag  = turb_vs.magnitude_component.reindex(ts.index)",
    "corr = turb_vs.correlation_component.reindex(ts.index)",
    "axes[0].fill_between(ts.index, mag,  alpha=0.7, color='#3498db', label='Magnitude')",
    "axes[0].fill_between(ts.index, corr, alpha=0.7, color='#9b59b6', label='Correlation')",
    "axes[0].set_ylabel('Component tau'); axes[0].legend(fontsize=9); axes[0].grid(alpha=0.15)",
    "axes[0].set_title('Turbulence Decomposition')",
    "total    = (mag + corr).clip(lower=1e-8)",
    "frac_cor = corr.clip(lower=0) / total",
    "axes[1].plot(frac_cor.index, frac_cor.rolling(21).mean(), color='#9b59b6', lw=1.1)",
    "axes[1].axhline(0.5, color='white', ls='--', lw=0.8, alpha=0.4)",
    "axes[1].set_ylabel('Fraction from correlation (21d MA)'); axes[1].grid(alpha=0.15)",
    "axes[1].set_ylim(0,1)",
    "axes[1].xaxis.set_major_formatter(mdates.DateFormatter('%Y'))",
    "plt.tight_layout(); plt.show()",
),

md("## 6 · Crisis Episode Table"),

code(
    "crisis_df   = crisis_episodes(turb_vs, regime='Crisis',   min_duration_days=3)",
    "turbulent_df = crisis_episodes(turb_vs, regime='Turbulent', min_duration_days=5)",
    "for label, eps in [('Crisis', crisis_df), ('Turbulent', turbulent_df)]:",
    "    print(f'{label} episodes: {len(eps)}')",
    "    if not eps.empty:",
    "        eps = eps.copy()",
    "        eps['start'] = pd.to_datetime(eps['start']).dt.strftime('%Y-%m-%d')",
    "        eps['end']   = pd.to_datetime(eps['end']).dt.strftime('%Y-%m-%d')",
    "        eps.columns  = ['Start','End','Duration (d)','Peak tau','Mean tau']",
    "        print(eps.round(2).to_string(index=False))",
    "    print()",
),

md("## 7 · Vol-Standardization Effect"),

code(
    "loc_spike  = panel.index.get_indexer(['2020-03-20'], method='nearest')[0]",
    "spike_date = panel.index[loc_spike]",
    "panel_spiked = panel.copy(); panel_spiked.loc[spike_date] *= 5.0",
    "t_vs  = compute_turbulence_index(panel_spiked, **kw)",
    "t_raw = compute_turbulence_index(panel_spiked, **{**kw, 'vol_standardize': False})",
    "print(f'Spike date : {spike_date.date()}')",
    "print(f'  vol-std  tau={t_vs.turbulence.loc[spike_date]:.1f}  regime={t_vs.regime.loc[spike_date]}')",
    "print(f'  raw      tau={t_raw.turbulence.loc[spike_date]:.1f}  regime={t_raw.regime.loc[spike_date]}')",
    "if t_vs.regime.loc[spike_date] != 'Crisis':",
    "    print('OK: vol-standardization suppressed the pure vol spike')",
    "else:",
    "    print('NOTE: spike still Crisis — EWMA adaptation may need more time')",
),

md("## 8 · Export to Excel"),

code(
    "from datetime import date",
    "os.makedirs('../exports', exist_ok=True)",
    "filename = f'../exports/02_turbulence_audit_{date.today()}.xlsx'",
    "with pd.ExcelWriter(filename, engine='openpyxl') as writer:",
    "    turb_vs.to_frame().to_excel(writer, sheet_name='Turbulence Panel')",
    "    turb_fx.to_frame().to_excel(writer, sheet_name='Turbulence FX')",
    "    turb_eq.to_frame().to_excel(writer, sheet_name='Turbulence Equity')",
    "    if not crisis_df.empty: crisis_df.to_excel(writer, sheet_name='Crisis Episodes', index=False)",
    "    replication_df.to_excel(writer, sheet_name='Manual Replication', index=False)",
    "    calibration_df.to_excel(writer, sheet_name='Chi2 Calibration', index=False)",
    "print(f'Exported: {filename}')",
),

])  # end 02


# ══════════════════════════════════════════════════════════════════════════════
# 03_factor_structure.ipynb
# ══════════════════════════════════════════════════════════════════════════════
save("03_factor_structure.ipynb", [

md("# 03 · Factor Structure",
   "PCA loadings, Kalman innovation norm, factor behaviour during COVID.",
   "Adjust parameters with the widgets below."),

code(
    "import sys, os",
    "sys.path.insert(0, os.path.join(os.getcwd(), '..'))",
    "import warnings; warnings.filterwarnings('ignore')",
    "import numpy as np",
    "import pandas as pd",
    "import matplotlib.pyplot as plt",
    "import matplotlib.dates as mdates",
    "import seaborn as sns",
    "from data.synthetic import generate_em_universe",
    "from modules.pca_kalman import compute_dynamic_factors_v2",
    "print('Imports OK')",
),

md("### Parameters (interactive)"),
WIDGET_CELL,
READ_PARAMS_CELL,

md("### Data & Computation"),

code(
    "uni   = generate_em_universe(seed=42, start=START)",
    "panel = uni.panel",
    "N_COMP = 3",
    "",
    "dyn = compute_dynamic_factors_v2(",
    "    panel, window=WINDOW, n_components=N_COMP, min_periods=60, lam=LAM)",
    "",
    "print(f'Panel  : {panel.shape}')",
    "print(f'Factors: {dyn.pca.factor_scores.shape}')",
    "print(f'innovation_norm non-null: {dyn.pca.innovation_norm.notna().sum()}')",
),

md("## 2 · Rolling Explained Variance by Factor"),

code(
    "scores    = dyn.pca.factor_scores.dropna()",
    "roll_var  = scores.rolling(WINDOW, min_periods=60).var()",
    "roll_tot  = roll_var.sum(axis=1)",
    "evr       = roll_var.div(roll_tot, axis=0).clip(0, 1)",
    "fcolors   = ['#e74c3c','#3498db','#2ecc71']",
    "",
    "fig, ax = plt.subplots(figsize=(13, 4))",
    "bottom = np.zeros(len(evr))",
    "for i, col in enumerate(evr.columns):",
    "    ax.fill_between(evr.index, bottom, bottom + evr[col].fillna(0),",
    "                    alpha=0.8, color=fcolors[i], label=col)",
    "    bottom = bottom + evr[col].fillna(0).values",
    "ax.set_ylabel(f'Rolling var share (window={WINDOW}d)')",
    "ax.set_title('Rolling Explained Variance by Factor')",
    "ax.legend(loc='upper right', fontsize=9); ax.grid(alpha=0.15)",
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))",
    "plt.tight_layout(); plt.show()",
),

md("## 3 · Latest Factor Loadings Heatmap",
   "> SVD sign is arbitrary — interpret the pattern, not the sign."),

code(
    "common_idx = scores.index.intersection(panel.index)",
    "load_mat   = pd.DataFrame(",
    "    {col: panel.loc[common_idx].corrwith(scores.loc[common_idx][col])",
    "     for col in scores.columns})",
    "",
    "fig, ax = plt.subplots(figsize=(7, 6))",
    "sns.heatmap(load_mat, annot=True, fmt='.2f', cmap='RdBu_r', center=0,",
    "            vmin=-1, vmax=1, linewidths=0.3, ax=ax, annot_kws={'size': 9})",
    "ax.set_title('Factor Loadings (full-sample corr of scores with returns)')",
    "ax.set_xlabel('Factor'); ax.set_ylabel('Asset')",
    "plt.tight_layout(); plt.show()",
),

md("## 4 · F1 Loading Evolution Per Asset Over Time"),

code(
    "ROLL = 63",
    "f1 = scores.iloc[:, 0]",
    "acolors = ['#00d4aa','#e74c3c','#f39c12','#9b59b6','#3498db',",
    "           '#1abc9c','#e67e22','#8e44ad','#2980b9','#27ae60']",
    "",
    "fig, ax = plt.subplots(figsize=(13, 5))",
    "for i, asset in enumerate(panel.columns):",
    "    common = f1.index.intersection(panel[asset].dropna().index)",
    "    rc = f1.loc[common].rolling(ROLL, min_periods=30).corr(panel[asset].loc[common])",
    "    ax.plot(rc.index, rc, label=asset, color=acolors[i % len(acolors)], lw=1.0, alpha=0.85)",
    "ax.axhline(0, color='white', lw=0.6, alpha=0.3)",
    "ax.set_ylabel(f'Rolling {ROLL}d corr with F1')",
    "ax.set_title('F1 Loading Evolution')",
    "ax.legend(fontsize=7, ncol=2); ax.grid(alpha=0.15)",
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))",
    "plt.tight_layout(); plt.show()",
),

md("## 5 · Kalman Innovation Norm  ||delta R||_F"),

code(
    "inorm = dyn.pca.innovation_norm.dropna()",
    "mu_i  = float(inorm.mean()); sd_i = float(inorm.std())",
    "thr   = mu_i + 2 * sd_i",
    "",
    "fig, ax = plt.subplots(figsize=(13, 3.5))",
    "ax.plot(inorm.index, inorm.values, color='#e74c3c', lw=0.9)",
    "ax.fill_between(inorm.index, inorm.values, alpha=0.15, color='#e74c3c')",
    "ax.axhline(thr,  color='#f39c12', ls='--', lw=1.0, label=f'mean+2sd={thr:.3f}')",
    "ax.axhline(mu_i, color='white',   ls=':',  lw=0.6, alpha=0.4)",
    "ax.set_ylabel('||delta R||_F'); ax.set_title('Correlation Regime Shock')",
    "ax.legend(fontsize=9); ax.grid(alpha=0.15)",
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))",
    "plt.tight_layout(); plt.show()",
),

md("## 6 · Innovation Spike Table"),

code(
    "spikes = inorm[inorm > thr].reset_index()",
    "spikes.columns = ['Date','||dR||_F']",
    "spikes['Date'] = spikes['Date'].dt.strftime('%Y-%m-%d')",
    "spikes['||dR||_F'] = spikes['||dR||_F'].round(4)",
    "print(f'Threshold (mean+2sd): {thr:.4f}   N spikes: {len(spikes)}')",
    "print(spikes.to_string(index=False))",
),

md("## 7 · Factor Scores During COVID (2020-01-01 to 2020-06-30)"),

code(
    "sc_covid = scores.loc['2020-01-01':'2020-06-30']",
    "fig, axes = plt.subplots(N_COMP, 1, figsize=(13, 2.5*N_COMP), sharex=True)",
    "for i, ax in enumerate(axes):",
    "    col = sc_covid.columns[i]",
    "    ax.plot(sc_covid.index, sc_covid[col], color=fcolors[i], lw=1.2)",
    "    ax.axhline(0, color='white', lw=0.5, alpha=0.3)",
    "    ax.set_ylabel(col); ax.grid(alpha=0.15); ax.set_title(f'{col} — COVID period')",
    "axes[-1].xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))",
    "plt.tight_layout(); plt.show()",
),

md("## 8 · Export to Excel"),

code(
    "from datetime import date",
    "os.makedirs('../exports', exist_ok=True)",
    "filename = f'../exports/03_factor_structure_{date.today()}.xlsx'",
    "with pd.ExcelWriter(filename, engine='openpyxl') as writer:",
    "    scores.to_excel(writer, sheet_name='Factor Scores')",
    "    dyn.to_frame().to_excel(writer, sheet_name='Kalman Filtered')",
    "    inorm.to_frame().to_excel(writer, sheet_name='Innovation Norm')",
    "    load_mat.to_excel(writer, sheet_name='Latest Loadings')",
    "    spikes.to_excel(writer, sheet_name='Innovation Spikes', index=False)",
    "    sc_covid.to_excel(writer, sheet_name='COVID Episode')",
    "print(f'Exported: {filename}')",
),

])  # end 03


# ══════════════════════════════════════════════════════════════════════════════
# 04_regime_analysis.ipynb
# ══════════════════════════════════════════════════════════════════════════════
save("04_regime_analysis.ipynb", [

md("# 04 · Regime Analysis",
   "Transition matrices, regime durations, AR vs tau conditioning, country ranking.",
   "Adjust parameters with the widgets below."),

code(
    "import sys, os",
    "sys.path.insert(0, os.path.join(os.getcwd(), '..'))",
    "import warnings; warnings.filterwarnings('ignore')",
    "import numpy as np",
    "import pandas as pd",
    "import matplotlib.pyplot as plt",
    "import matplotlib.dates as mdates",
    "import seaborn as sns",
    "from data.synthetic import generate_em_universe",
    "from modules.turbulence import compute_turbulence_index",
    "from modules.absorption import compute_absorption_ratio",
    "print('Imports OK')",
),

md("### Parameters (interactive)"),
WIDGET_CELL,
READ_PARAMS_CELL,

md("### Data & Computation"),

code(
    "REGIMES = ['Calm','Elevated','Turbulent','Crisis']",
    "",
    "uni    = generate_em_universe(seed=42, start=START)",
    "panel  = uni.panel",
    "fx_ret = uni.fx",
    "eq_ret = uni.equity",
    "fx_cols = list(fx_ret.columns)",
    "eq_cols = list(eq_ret.columns)",
    "",
    "kw   = dict(window=WINDOW, min_periods=60, vol_standardize=VOL_STD, slow_window=SLOW_W)",
    "turb = compute_turbulence_index(panel,  **kw)",
    "ar   = compute_absorption_ratio(fx_ret, window=WINDOW, min_periods=60, lam=LAM)",
    "",
    "country_turb = {}",
    "for i, col in enumerate(fx_cols):",
    "    ct = pd.concat([fx_ret[[col]], eq_ret[[eq_cols[i]]]], axis=1)",
    "    country_turb[col] = compute_turbulence_index(ct, **kw)",
    "",
    "print(f'Regime: {turb.current_regime()}   AR: {float(ar.absorption_ratio.dropna().iloc[-1]):.4f}')",
),

md("## 2 · Regime Transition Matrix  P(regime_{t+1} | regime_t)"),

code(
    "reg = turb.regime.dropna()",
    "trans = pd.DataFrame(0, index=REGIMES, columns=REGIMES, dtype=float)",
    "for t in range(len(reg)-1):",
    "    r_t, r_t1 = reg.iloc[t], reg.iloc[t+1]",
    "    if r_t in REGIMES and r_t1 in REGIMES: trans.loc[r_t, r_t1] += 1",
    "trans_pct = trans.div(trans.sum(axis=1), axis=0).round(3)",
    "",
    "fig, ax = plt.subplots(figsize=(6, 4.5))",
    "sns.heatmap(trans_pct, annot=True, fmt='.3f', cmap='Blues',",
    "            vmin=0, vmax=1, linewidths=0.4, ax=ax, annot_kws={'size': 11})",
    "ax.set_title('Empirical Regime Transition Matrix P(t+1 | t)')",
    "ax.set_xlabel('Regime at t+1'); ax.set_ylabel('Regime at t')",
    "plt.tight_layout(); plt.show()",
    "print(trans_pct.to_string())",
),

md("## 3 · Average Regime Duration"),

code(
    "durations = {r: [] for r in REGIMES}",
    "cur_r, cur_n = None, 0",
    "for r in reg:",
    "    if r == cur_r: cur_n += 1",
    "    else:",
    "        if cur_r in REGIMES and cur_n > 0: durations[cur_r].append(cur_n)",
    "        cur_r, cur_n = r, 1",
    "if cur_r in REGIMES and cur_n > 0: durations[cur_r].append(cur_n)",
    "",
    "dur_rows = []",
    "for r in REGIMES:",
    "    vals = durations[r]",
    "    if vals: dur_rows.append({'Regime': r, 'N episodes': len(vals),",
    "        'Mean (d)': round(np.mean(vals),1), 'Median (d)': round(np.median(vals),1), 'Max (d)': max(vals)})",
    "dur_df = pd.DataFrame(dur_rows).set_index('Regime')",
    "print(dur_df.to_string())",
),

md("## 4 · AR Level Conditioned on Turbulence Regime",
   "High AR + high tau: systemic.  High tau + low AR: idiosyncratic."),

code(
    "common = turb.regime.index.intersection(ar.absorption_ratio.index)",
    "df_j   = pd.DataFrame({'regime': turb.regime.loc[common],",
    "                        'AR': ar.absorption_ratio.loc[common]}).dropna()",
    "reg_colors = {'Calm':'#2ecc71','Elevated':'#f39c12','Turbulent':'#e67e22','Crisis':'#e74c3c'}",
    "fig, ax = plt.subplots(figsize=(8, 4))",
    "for i, r in enumerate(REGIMES):",
    "    vals = df_j.loc[df_j['regime'] == r, 'AR']",
    "    if len(vals) == 0: continue",
    "    ax.boxplot(vals, positions=[i], widths=0.5, patch_artist=True,",
    "               boxprops=dict(facecolor=reg_colors[r], alpha=0.7),",
    "               medianprops=dict(color='white', lw=2),",
    "               whiskerprops=dict(color=reg_colors[r]), capprops=dict(color=reg_colors[r]),",
    "               flierprops=dict(marker='.', color=reg_colors[r], alpha=0.3))",
    "ax.set_xticks(range(len(REGIMES))); ax.set_xticklabels(REGIMES)",
    "ax.set_ylabel('Absorption Ratio'); ax.set_title('AR by Turbulence Regime')",
    "ax.grid(axis='y', alpha=0.2)",
    "plt.tight_layout(); plt.show()",
    "ar_by_regime = df_j.groupby('regime')['AR'].agg(['mean','median','std']).round(4)",
    "print(ar_by_regime.to_string())",
),

md("## 5 · Country Stress Rank — Monthly Heatmap"),

code(
    "monthly = pd.DataFrame({c: country_turb[c].turbulence.resample('MS').mean()",
    "                         for c in fx_cols})",
    "monthly_z = (monthly - monthly.mean(axis=1).values[:,None]) / (monthly.std(axis=1).values[:,None] + 1e-8)",
    "",
    "fig, ax = plt.subplots(figsize=(14, 4))",
    "im = ax.imshow(monthly_z.T.values, aspect='auto', cmap='RdYlGn_r', vmin=-2, vmax=2)",
    "ax.set_yticks(range(len(fx_cols))); ax.set_yticklabels(fx_cols)",
    "yr_ticks = [i for i, d in enumerate(monthly.index) if d.month == 1]",
    "ax.set_xticks(yr_ticks); ax.set_xticklabels([monthly.index[i].year for i in yr_ticks])",
    "plt.colorbar(im, ax=ax, label='Turbulence z-score (cross-country)')",
    "ax.set_title('Country Stress Rank — Monthly Turbulence Z-score')",
    "plt.tight_layout(); plt.show()",
),

md("## 6 · Country tau Correlation with Panel tau"),

code(
    "ROLL = 63",
    "panel_tau = turb.turbulence.dropna()",
    "acolors   = ['#00d4aa','#e74c3c','#f39c12','#9b59b6','#3498db']",
    "",
    "panel_corr_df = {}",
    "fig, ax = plt.subplots(figsize=(13, 4))",
    "for i, col in enumerate(fx_cols):",
    "    ct_tau = country_turb[col].turbulence.dropna()",
    "    common = panel_tau.index.intersection(ct_tau.index)",
    "    rc = panel_tau.loc[common].rolling(ROLL).corr(ct_tau.loc[common])",
    "    panel_corr_df[col] = rc",
    "    ax.plot(rc.index, rc, label=col, color=acolors[i], lw=1.1, alpha=0.85)",
    "ax.axhline(0,   color='white',  lw=0.5, alpha=0.3)",
    "ax.axhline(0.7, color='orange', ls='--', lw=0.7, alpha=0.5)",
    "ax.set_ylabel(f'{ROLL}d rolling corr with panel tau')",
    "ax.set_title('Country Turbulence Correlation with Panel tau')",
    "ax.legend(fontsize=9); ax.grid(alpha=0.15)",
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))",
    "plt.tight_layout(); plt.show()",
    "panel_corr_df = pd.DataFrame(panel_corr_df)",
),

md("## 7 · Export to Excel"),

code(
    "from datetime import date",
    "os.makedirs('../exports', exist_ok=True)",
    "filename = f'../exports/04_regime_analysis_{date.today()}.xlsx'",
    "with pd.ExcelWriter(filename, engine='openpyxl') as writer:",
    "    trans_pct.to_excel(writer, sheet_name='Transition Matrix')",
    "    dur_df.to_excel(writer, sheet_name='Regime Durations')",
    "    df_j.groupby('regime')['AR'].describe().to_excel(writer, sheet_name='AR by Regime')",
    "    monthly.to_excel(writer, sheet_name='Country Stress Rank')",
    "    panel_corr_df.to_excel(writer, sheet_name='Country Panel Corr')",
    "print(f'Exported: {filename}')",
),

])  # end 04


# ══════════════════════════════════════════════════════════════════════════════
# 05_methodology_sandbox.ipynb
# ══════════════════════════════════════════════════════════════════════════════
save("05_methodology_sandbox.ipynb", [

md("# 05 · Methodology Sandbox",
   "Experimental area.  Validated code gets promoted to `modules/`."),

code(
    "import sys, os",
    "sys.path.insert(0, os.path.join(os.getcwd(), '..'))",
    "import warnings; warnings.filterwarnings('ignore')",
    "import numpy as np",
    "import pandas as pd",
    "import matplotlib.pyplot as plt",
    "from data.synthetic import generate_em_universe",
    "from modules.turbulence import compute_turbulence_index",
    "from modules.absorption import compute_absorption_ratio",
    "from modules.pca_kalman import compute_dynamic_factors_v2",
    "from core.covariance import SlowCovariance, FastCovariance, VolStandardizer, KalmanCorrelation",
    "uni = generate_em_universe(seed=42)",
    "panel = uni.panel; fx_ret = uni.fx; eq_ret = uni.equity",
    "print('Setup complete. panel shape:', panel.shape)",
),

md("## Section A — DCC-GARCH Experiment",
   "Target: replace EWMA R_t with DCC R_t in the KalmanCorrelation pipeline."),

code(
    "# Develop here, then promote to modules/ when validated",
    "#",
    "# DCC-GARCH plan (Engle 2002):",
    "#   1. Fit univariate GARCH(1,1) per series -> standardized residuals e_t",
    "#   2. Q_t = (1-a-b)*Q_bar + a*(e_{t-1} @ e_{t-1}.T) + b*Q_{t-1}",
    "#   3. R_t_DCC = diag(Q_t)^{-1/2} @ Q_t @ diag(Q_t)^{-1/2}",
    "#   4. Compare lead time of R_t_DCC vs R_t_EWMA at stress onset",
    "#",
    "# Candidate library: arch  (pip install arch)",
    "#",
    "pass",
),

md("## Section B — Spillover Metrics Experiment",
   "Diebold-Yilmaz (2012) variance decomposition spillover table."),

code(
    "# Develop here, then promote to modules/ when validated",
    "#",
    "# Spillover plan:",
    "#   1. VAR(p) on panel returns -> FEVD",
    "#   2. Spillover_i->j = fraction of j FEVD from i shocks",
    "#   3. Total spillover = sum(off-diag FEVD) / N",
    "#   4. Rolling 252d: track evolution",
    "#",
    "# from statsmodels.tsa.vector_ar.var_model import VAR",
    "#",
    "pass",
),

md("## Section C — New Metric Development Area"),

code(
    "# Develop here, then promote to modules/ when validated",
    "#",
    "# Ideas:",
    "#   - Mahalanobis distance on changes in R_t (second-derivative signal)",
    "#   - Network centrality: country PageRank on rolling partial-corr graph",
    "#   - Entropy of eigenvalue distribution as AR alternative",
    "#   - Cross-entropy(R_t_current, R_t_calm) for regime detection",
    "#",
    "pass",
),

md("## Export (placeholder)"),

code(
    "from datetime import date",
    "os.makedirs('../exports', exist_ok=True)",
    "filename = f'../exports/05_sandbox_{date.today()}.xlsx'",
    "with pd.ExcelWriter(filename, engine='openpyxl') as writer:",
    "    pd.DataFrame({'placeholder': ['Edit this sandbox and add exports here']}).to_excel(",
    "        writer, sheet_name='Sandbox Export', index=False)",
    "print(f'Exported: {filename}')",
),

])  # end 05

print("Done.")
