"""
Generator for notebooks/06_dynamic_factor_model.ipynb  (v2)

Theoretical change from v1:
  - Filter PARAMETERS (loadings + eigenvalues), not factor scores as states.
  - EWMA R_t from FastCovariance as input, not rolling sample cov.
  - Factor alignment (Hungarian + sign + similarity) before every update.
  - Moment-based parameter calibration, no MLE.
  - Contemporaneous factor decomposition (OLS projection onto smoothed loadings).

Run from em_risk_dashboard/ directory.
"""
import json, pathlib, uuid

NB_DIR = pathlib.Path("notebooks")


def new_id():
    return uuid.uuid4().hex[:8]


def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12.0"},
        },
        "cells": cells,
    }


def md(*lines):
    return {
        "id": new_id(), "cell_type": "markdown", "metadata": {},
        "source": [l + "\n" for l in lines],
    }


def code(*lines):
    return {
        "id": new_id(), "cell_type": "code", "execution_count": None,
        "metadata": {}, "outputs": [],
        "source": [l + "\n" for l in lines],
    }


def save(name, cells):
    p = NB_DIR / name
    with open(p, "w") as f:
        json.dump(nb(cells), f, indent=1)
    print(f"  wrote {p}")


# ═══════════════════════════════════════════════════════════════════════════════
save("06_dynamic_factor_model.ipynb", [

md(
    "# 06 · Dynamic Factor Model v2",
    "",
    "**What we filter:** Not factor scores — the PARAMETERS of the covariance structure.",
    "- **Filter A:** factor loading directions (eigenvectors of R_hat_t)",
    "- **Filter B:** factor variances (eigenvalues of R_hat_t)",
    "",
    "**Input:** EWMA correlation R_hat_t from FastCovariance (λ=0.94).",
    "",
    "**Factor shocks** are a *contemporaneous decomposition* of observed returns",
    "onto the smoothed factor structure — not a prediction.",
    "",
    "State space:",
    "```",
    "  Filter A:  v_k_t  = v_k_{t-1}  + η_t,   η ~ N(0, q_v · I_N)     [loading direction]",
    "  Filter B:  λ_k_t  = φ λ_k_{t-1} + η_t,  η ~ N(0, q_λ)           [factor variance]",
    "  Observation A: v̂_k_t ~ N(v_k_t, r_v · I_N)",
    "  Observation B: λ̂_k_t ~ N(λ_k_t, r_λ)",
    "```",
    "Parameters calibrated from training window 2015–2019 (moment estimators).",
),

# ── Cell 1: Setup ──────────────────────────────────────────────────────────
code(
    "import sys, os",
    "sys.path.insert(0, os.path.join(os.getcwd(), '..'))",
    "import warnings; warnings.filterwarnings('ignore')",
    "",
    "import numpy as np",
    "import pandas as pd",
    "from scipy.optimize import linear_sum_assignment",
    "from scipy import linalg, stats as sp_stats",
    "import plotly.graph_objects as go",
    "from plotly.subplots import make_subplots",
    "from datetime import date",
    "",
    "from data.fetcher import load_em_universe",
    "from core.returns import log_returns",
    "from core.covariance import FastCovariance",
    "from modules.turbulence import compute_turbulence_index",
    "",
    "raw   = load_em_universe(start='2015-01-01', use_cache=True)",
    "fx    = log_returns(raw['fx'])",
    "eq    = log_returns(raw['equity'])",
    "eq.columns = ['CHL', 'BRA', 'MEX', 'COL', 'PER']",
    "gl    = log_returns(raw['global'])",
    "panel = pd.concat([fx, eq, gl], axis=1).dropna(how='all')",
    "N     = panel.shape[1]",
    "print(f'Panel: {panel.shape}')",
    "print(f'Assets: {list(panel.columns)}')",
    "",
    "kw   = dict(window=252, min_periods=60, vol_standardize=True, slow_window=504)",
    "turb = compute_turbulence_index(panel, **kw)",
    "print('Turbulence computed.')",
),

md("## Cell 2 — Rolling EWMA correlation matrices and eigendecomposition"),

# ── Cell 2 ─────────────────────────────────────────────────────────────────
code(
    "def compute_rolling_eigen(",
    "    returns: pd.DataFrame,",
    "    window: int = 252,",
    "    lam: float = 0.94,",
    "    K_min: int = 2,",
    "    K_max: int = 5,",
    "    min_periods: int = 60,",
    ") -> dict:",
    "    \"\"\"",
    "    Compute EWMA R_hat_t at each date, eigendecompose, apply MP threshold.",
    "",
    "    Uses FastCovariance.fit_rolling (single EWMA pass) for R_t.",
    "    D_t (conditional vols) computed in a parallel scalar EWMA pass.",
    "    MP: gamma_t = N / min(t+1, window), sigma2_t = median eigenvalue.",
    "    \"\"\"",
    "    N_assets = returns.shape[1]",
    "    T_full   = len(returns)",
    "    dates_all = returns.index",
    "    X = returns.fillna(0.0).values",
    "",
    "    # Single-pass EWMA for R_t via FastCovariance",
    "    fc = FastCovariance()",
    "    R_series = fc.fit_rolling(returns, lam=lam)  # list of N x N matrices",
    "",
    "    # Parallel scalar EWMA for conditional vols (D_t diagonal)",
    "    burn = min(63, max(T_full // 4, N_assets + 1))",
    "    var_ewma = np.var(X[:burn], axis=0)",
    "    var_ewma = np.maximum(var_ewma, 1e-12)",
    "    d_vecs   = []",
    "    for i in range(T_full):",
    "        var_ewma = lam * var_ewma + (1.0 - lam) * X[i] ** 2",
    "        d_vecs.append(np.sqrt(np.maximum(var_ewma, 1e-12)).copy())",
    "",
    "    V_hat_d      = {}",
    "    lam_hat_d    = {}",
    "    K_t_d        = {}",
    "    lplus_d      = {}",
    "    lnoise_d     = {}",
    "    D_hat_d      = {}",
    "",
    "    for i, dt in enumerate(dates_all):",
    "        if i < min_periods - 1:",
    "            continue",
    "",
    "        R_t   = R_series[i]",
    "        T_eff = min(i + 1, window)",
    "",
    "        # Eigendecompose (eigh returns ascending; sort descending)",
    "        eigvals, eigvecs = np.linalg.eigh(R_t)",
    "        order   = np.argsort(eigvals)[::-1]",
    "        eigvals = eigvals[order]",
    "        eigvecs = eigvecs[:, order]",
    "",
    "        # Marchenko-Pastur threshold",
    "        gamma_t      = N_assets / T_eff",
    "        sigma2_t     = np.median(eigvals)",
    "        lambda_plus  = sigma2_t * (1.0 + np.sqrt(gamma_t)) ** 2",
    "        K_raw = int(np.sum(eigvals > lambda_plus))",
    "        K_t   = max(K_min, min(K_max, K_raw))",
    "",
    "        noise_eigs   = eigvals[K_t:]",
    "        lambda_noise = float(np.mean(noise_eigs)) if len(noise_eigs) > 0 else float(sigma2_t)",
    "",
    "        # Top K_max eigenvectors; sign: largest |element| positive",
    "        V_top = eigvecs[:, :K_max].copy()",
    "        for k in range(K_max):",
    "            if V_top[np.argmax(np.abs(V_top[:, k])), k] < 0:",
    "                V_top[:, k] *= -1",
    "",
    "        V_hat_d[dt]   = V_top",
    "        lam_hat_d[dt] = eigvals[:K_max].copy()",
    "        K_t_d[dt]     = K_t",
    "        lplus_d[dt]   = lambda_plus",
    "        lnoise_d[dt]  = lambda_noise",
    "        D_hat_d[dt]   = d_vecs[i].copy()",
    "",
    "    dates_out = pd.DatetimeIndex(sorted(V_hat_d.keys()))",
    "    return {",
    "        'V_hat':       V_hat_d,",
    "        'lambda_hat':  lam_hat_d,",
    "        'K_t':         pd.Series(K_t_d, name='K_t'),",
    "        'lambda_plus':  pd.Series(lplus_d,  name='lambda_plus'),",
    "        'lambda_noise': pd.Series(lnoise_d, name='lambda_noise'),",
    "        'D_hat':        D_hat_d,",
    "        'dates':        dates_out,",
    "    }",
    "",
    "",
    "print('Computing rolling EWMA eigendecomposition...')",
    "K_max       = 5",
    "eigen_result = compute_rolling_eigen(panel, window=252, lam=0.94, K_max=K_max)",
    "",
    "print(f\"Valid dates:   {len(eigen_result['dates'])}\")",
    "print(f\"K_t range:     {eigen_result['K_t'].min()} to {eigen_result['K_t'].max()}  \"",
    "      f\"mean={eigen_result['K_t'].mean():.2f}\")",
    "print(f\"lambda_noise:  {eigen_result['lambda_noise'].min():.6f} \"",
    "      f\"to {eigen_result['lambda_noise'].max():.6f}\")",
    "",
    "# Show raw eigenvectors at key dates (unfiltered — choppy, signs inconsistent)",
    "fcols = [f'F{k+1}' for k in range(K_max)]",
    "for ds in ['2018-01-02', '2020-03-20', '2024-12-31']:",
    "    ts  = pd.Timestamp(ds)",
    "    avail = eigen_result['dates']",
    "    near  = avail[max(0, avail.searchsorted(ts, side='right') - 1)] if ts >= avail[0] else avail[0]",
    "    K_at  = int(eigen_result['K_t'].loc[near])",
    "    Lam   = eigen_result['V_hat'][near][:, :K_at]",
    "    df_   = pd.DataFrame(Lam, index=list(panel.columns),",
    "                         columns=[f'F{k+1}' for k in range(K_at)])",
    "    print(f'\\nRaw eigenvectors {near.date()} (K_t={K_at}) [unfiltered]:',)",
    "    print(df_.round(3).to_string())",
),

md("## Cell 3 — Parameter calibration (training window 2015–2019)"),

# ── Cell 3 ─────────────────────────────────────────────────────────────────
code(
    "def calibrate_parameters(eigen_result: dict, train_end: str = '2019-12-31') -> dict:",
    "    \"\"\"",
    "    Estimate filter parameters from training window.",
    "",
    "    Filter A (loading filter):",
    "      q_v = mean squared day-to-day change per element (sign-aligned pairs)",
    "      r_v = q_v / SNR_target  (SNR_target=0.1 -> obs is 10x noisier than state)",
    "",
    "    Filter B (eigenvalue filter):",
    "      phi      = mean OLS AR(1) coefficient across K_max factors",
    "      q_lambda = mean AR(1) residual variance",
    "      r_lambda = mean variance of deviation from 21d rolling mean",
    "    \"\"\"",
    "    train_end_ts = pd.Timestamp(train_end)",
    "    dates_tr = [d for d in eigen_result['dates'] if d <= train_end_ts]",
    "    K_max_   = len(list(eigen_result['lambda_hat'].values())[0])   # should be K_max",
    "",
    "    # ── Filter A: q_v ─────────────────────────────────────────────────────",
    "    sq_changes = []",
    "    for i in range(1, len(dates_tr)):",
    "        dt_prev, dt_curr = dates_tr[i - 1], dates_tr[i]",
    "        V_prev = eigen_result['V_hat'][dt_prev]   # N x K_max",
    "        V_curr = eigen_result['V_hat'][dt_curr]",
    "        for k in range(K_max_):",
    "            sim = float(V_curr[:, k] @ V_prev[:, k])",
    "            v_al = (np.sign(sim) if sim != 0 else 1.0) * V_curr[:, k]",
    "            delta = v_al - V_prev[:, k]",
    "            sq_changes.append(float(np.mean(delta ** 2)))",
    "",
    "    q_v = float(np.mean(sq_changes)) if sq_changes else 1e-5",
    "    r_v = q_v / 0.1   # SNR_target = 0.1",
    "",
    "    # ── Filter B: phi, q_lambda, r_lambda ─────────────────────────────────",
    "    lam_mat = np.array([eigen_result['lambda_hat'][d] for d in dates_tr])  # T x K_max",
    "",
    "    phis, q_lams, r_lams = [], [], []",
    "    for k in range(K_max_):",
    "        y = lam_mat[1:, k]",
    "        x = lam_mat[:-1, k]",
    "        denom = float(x @ x)",
    "        phi_k = float(x @ y) / denom if denom > 1e-12 else 0.9",
    "        phi_k = max(0.5, min(0.99, phi_k))",
    "        resid = y - phi_k * x",
    "        phis.append(phi_k)",
    "        q_lams.append(float(np.var(resid)))",
    "",
    "        lk   = pd.Series([eigen_result['lambda_hat'][d][k] for d in dates_tr],",
    "                          index=pd.DatetimeIndex(dates_tr))",
    "        dev  = lk - lk.rolling(21, min_periods=5).mean()",
    "        r_lams.append(float(dev.dropna().var()))",
    "",
    "    phi      = max(0.5, min(0.99, float(np.mean(phis))))",
    "    q_lambda = float(np.mean(q_lams))",
    "    r_lambda = float(np.mean(r_lams))",
    "    r_lambda = max(r_lambda, q_lambda * 0.01)   # numerical floor",
    "",
    "    return {",
    "        'q_v':       q_v,",
    "        'r_v':       r_v,",
    "        'phi':       phi,",
    "        'q_lambda':  q_lambda,",
    "        'r_lambda':  r_lambda,",
    "        'SNR_v':     q_v / r_v,",
    "        'SNR_lambda': q_lambda / r_lambda,",
    "    }",
    "",
    "",
    "params = calibrate_parameters(eigen_result, train_end='2019-12-31')",
    "",
    "print('Filter A (loading filter):')",
    "print(f\"  q_v (state noise):       {params['q_v']:.8f}\")",
    "print(f\"  r_v (obs noise):         {params['r_v']:.8f}\")",
    "print(f\"  SNR (q_v/r_v):           {params['SNR_v']:.4f}  (target: 0.10)\")",
    "print('Filter B (eigenvalue filter):')",
    "print(f\"  phi (mean reversion):    {params['phi']:.4f}\")",
    "print(f\"  q_lambda (state noise):  {params['q_lambda']:.8f}\")",
    "print(f\"  r_lambda (obs noise):    {params['r_lambda']:.8f}\")",
    "print(f\"  SNR (q_lam/r_lam):       {params['SNR_lambda']:.4f}\")",
    "print('Interpretation:')",
    "_hl_v   = 0.5 / params['q_v'] if params['q_v'] > 0 else float('inf')",
    "_hl_lam = np.log(0.5) / np.log(params['phi']) if params['phi'] < 1 else float('inf')",
    "print(f\"  Loading half-life (approx): {_hl_v:.1f} days\")",
    "print(f\"  Eigenvalue reversion: phi={params['phi']:.4f} -> half-life={_hl_lam:.1f} days\")",
),

md("## Cell 4 — Factor alignment function"),

# ── Cell 4 ─────────────────────────────────────────────────────────────────
code(
    "def align_factors(",
    "    V_new: np.ndarray,",
    "    lam_new: np.ndarray,",
    "    V_prev: np.ndarray,",
    "    sim_threshold: float = 0.5,",
    "):",
    "    \"\"\"",
    "    Match, reorder, sign-align new eigenvectors to previous filtered loadings.",
    "",
    "    Step 1 — Hungarian matching on |inner product| matrix (handles reordering).",
    "    Step 2 — Sign alignment (handles SVD sign ambiguity).",
    "    Step 3 — Similarity check (flags genuine structural rotations).",
    "",
    "    Returns",
    "    -------",
    "    V_aligned    : N x K, aligned eigenvectors",
    "    lam_aligned  : K, reordered eigenvalues",
    "    similarities : K, dot product similarities after alignment",
    "    rotation_flags: list of factor indices with similarity < sim_threshold",
    "    \"\"\"",
    "    K = V_new.shape[1]",
    "",
    "    # Step 1: Hungarian on absolute inner product matrix",
    "    C = np.abs(V_new.T @ V_prev)          # K x K",
    "    row_ind, col_ind = linear_sum_assignment(-C)",
    "    V_reord  = V_new[:, col_ind]",
    "    lam_reord = lam_new[col_ind]",
    "",
    "    # Step 2: Sign alignment",
    "    V_aligned    = V_reord.copy()",
    "    similarities = np.zeros(K)",
    "    for i in range(K):",
    "        sim = float(V_reord[:, i] @ V_prev[:, i])",
    "        V_aligned[:, i] = np.sign(sim) * V_reord[:, i] if sim != 0 else V_reord[:, i]",
    "        similarities[i] = abs(sim)",
    "",
    "    # Step 3: Rotation flags",
    "    rotation_flags = [i for i in range(K) if similarities[i] < sim_threshold]",
    "",
    "    return V_aligned, lam_reord, similarities, rotation_flags",
    "",
    "",
    "# ── Test: alignment between two consecutive dates ─────────────────────",
    "avail = list(eigen_result['dates'])",
    "dt0, dt1 = avail[100], avail[101]",
    "V0 = eigen_result['V_hat'][dt0][:, :eigen_result['K_t'].loc[dt0]]",
    "V1 = eigen_result['V_hat'][dt1][:, :eigen_result['K_t'].loc[dt1]]",
    "K_min2 = min(V0.shape[1], V1.shape[1])",
    "V1_al, lam1_al, sims_test, rot_test = align_factors(",
    "    V1[:, :K_min2], eigen_result['lambda_hat'][dt1][:K_min2],",
    "    V0[:, :K_min2]",
    ")",
    "print(f'Alignment test ({dt0.date()} -> {dt1.date()}):',)",
    "print(f'  Similarities: {sims_test.round(4)}')",
    "print(f'  Rotation flags: {rot_test}')",
    "print(f'  All similarities close to 1.0 in calm periods: {(sims_test > 0.8).all()}')",
),

md("## Cell 5 — Run Kalman filters on loadings and eigenvalues"),

# ── Cell 5 ─────────────────────────────────────────────────────────────────
code(
    "def run_kalman_filters(",
    "    eigen_result: dict,",
    "    params: dict,",
    "    K_max: int = 5,",
    "    sim_threshold: float = 0.5,",
    ") -> dict:",
    "    \"\"\"",
    "    Run Filter A (loading directions) and Filter B (eigenvalues).",
    "",
    "    Filter A: scalar Kalman per factor on N-dim loading vector.",
    "      P_v is a single scalar (same variance for all N elements).",
    "      Kalman gain down-weighted by similarity^2 when rotation detected.",
    "",
    "    Filter B: scalar Kalman per factor on eigenvalue.",
    "      AR(1) transition with mean reversion phi.",
    "      Inactive factors (k >= K_t) run prediction-only step (drift to 0).",
    "    \"\"\"",
    "    dates = list(eigen_result['dates'])",
    "    N_assets = eigen_result['V_hat'][dates[0]].shape[0]",
    "    fcols = [f'F{k+1}' for k in range(K_max)]",
    "",
    "    q_v, r_v  = params['q_v'],  params['r_v']",
    "    phi        = params['phi']",
    "    q_lam      = params['q_lambda']",
    "    r_lam      = params['r_lambda']",
    "",
    "    # ── Initialize from first date ──────────────────────────────────────",
    "    first_dt = dates[0]",
    "    V_bar   = eigen_result['V_hat'][first_dt].copy()        # N x K_max",
    "    P_v     = np.full(K_max, r_v)                           # scalar per factor",
    "    lam_bar = eigen_result['lambda_hat'][first_dt].copy()   # K_max",
    "    P_lam   = np.full(K_max, r_lam)",
    "",
    "    # Storage lists",
    "    V_bar_hist    = {first_dt: V_bar.copy()}",
    "    lam_bar_hist  = [lam_bar.copy()]",
    "    P_v_hist      = [P_v.copy()]",
    "    P_lam_hist    = [P_lam.copy()]",
    "    sims_hist     = [np.ones(K_max)]",
    "    kg_v_hist     = [np.zeros(K_max)]",
    "    kg_lam_hist   = [np.zeros(K_max)]",
    "    lnorm_hist    = [0.0]",
    "    enorm_hist    = [0.0]",
    "    rot_events    = []",
    "    dates_out     = [first_dt]",
    "",
    "    for t_idx in range(1, len(dates)):",
    "        dt        = dates[t_idx]",
    "        V_hat_t   = eigen_result['V_hat'][dt]       # N x K_max",
    "        lam_hat_t = eigen_result['lambda_hat'][dt]  # K_max",
    "        K_t       = int(eigen_result['K_t'].loc[dt])",
    "",
    "        # Save prior state for innovation computation",
    "        V_bar_prev  = V_bar[:, :K_t].copy()",
    "        lam_bar_prev = lam_bar[:K_t].copy()",
    "",
    "        # ── Alignment ──────────────────────────────────────────────────",
    "        V_aligned, lam_aligned, sims_k, rot_flags = align_factors(",
    "            V_hat_t[:, :K_t],",
    "            lam_hat_t[:K_t],",
    "            V_bar[:, :K_t],",
    "            sim_threshold,",
    "        )",
    "",
    "        sims_full = np.ones(K_max)",
    "        sims_full[:K_t] = sims_k",
    "        kg_v_full   = np.zeros(K_max)",
    "        kg_lam_full = np.zeros(K_max)",
    "",
    "        # ── Filter A: loading directions ────────────────────────────────",
    "        for k in range(K_t):",
    "            r_v_eff = r_v / max(sims_k[k] ** 2, 0.01)   # inflate noise at low sim",
    "            P_pred  = P_v[k] + q_v",
    "            K_g     = P_pred / (P_pred + r_v_eff)",
    "            V_bar[:, k] = V_bar[:, k] + K_g * (V_aligned[:, k] - V_bar[:, k])",
    "            P_v[k]      = (1.0 - K_g) * P_pred",
    "            nrm = np.linalg.norm(V_bar[:, k])",
    "            if nrm > 1e-10:",
    "                V_bar[:, k] /= nrm",
    "            kg_v_full[k] = K_g",
    "",
    "        # ── Filter B: eigenvalues (all K_max, inactive = predict only) ──",
    "        for k in range(K_max):",
    "            lam_pred  = phi * lam_bar[k]",
    "            P_pred_lam = phi ** 2 * P_lam[k] + q_lam",
    "            if k < K_t:",
    "                K_g_lam    = P_pred_lam / (P_pred_lam + r_lam)",
    "                lam_bar[k] = lam_pred + K_g_lam * (lam_aligned[k] - lam_pred)",
    "                P_lam[k]   = (1.0 - K_g_lam) * P_pred_lam",
    "                kg_lam_full[k] = K_g_lam",
    "            else:",
    "                lam_bar[k] = lam_pred    # drift toward 0 when inactive",
    "                P_lam[k]   = P_pred_lam",
    "            lam_bar[k] = max(lam_bar[k], 1e-8)",
    "",
    "        # ── Innovations (computed vs prior state, before this update) ───",
    "        load_innov = V_aligned - V_bar_prev          # N x K_t",
    "        eig_innov  = lam_aligned - lam_bar_prev      # K_t",
    "        lnorm = float(np.linalg.norm(load_innov, 'fro'))",
    "        enorm = float(np.linalg.norm(eig_innov))",
    "",
    "        for k_flag in rot_flags:",
    "            rot_events.append({'date': dt, 'factor_k': k_flag + 1,",
    "                               'similarity': float(sims_k[k_flag])})",
    "",
    "        V_bar_hist[dt] = V_bar.copy()",
    "        lam_bar_hist.append(lam_bar.copy())",
    "        P_v_hist.append(P_v.copy())",
    "        P_lam_hist.append(P_lam.copy())",
    "        sims_hist.append(sims_full.copy())",
    "        kg_v_hist.append(kg_v_full.copy())",
    "        kg_lam_hist.append(kg_lam_full.copy())",
    "        lnorm_hist.append(lnorm)",
    "        enorm_hist.append(enorm)",
    "        dates_out.append(dt)",
    "",
    "    dti = pd.DatetimeIndex(dates_out)",
    "    rot_df = (pd.DataFrame(rot_events) if rot_events",
    "              else pd.DataFrame(columns=['date', 'factor_k', 'similarity']))",
    "",
    "    return {",
    "        'V_bar':              V_bar_hist,",
    "        'lam_bar':            np.array(lam_bar_hist),",
    "        'P_v':                pd.DataFrame(P_v_hist,    index=dti, columns=fcols),",
    "        'P_lam':              pd.DataFrame(P_lam_hist,  index=dti, columns=fcols),",
    "        'similarities':       pd.DataFrame(sims_hist,   index=dti, columns=fcols),",
    "        'K_gain_v':           pd.DataFrame(kg_v_hist,   index=dti, columns=fcols),",
    "        'K_gain_lam':         pd.DataFrame(kg_lam_hist, index=dti, columns=fcols),",
    "        'loading_innov_norm': pd.Series(lnorm_hist, index=dti, name='loading_innov_norm'),",
    "        'eigen_innov_norm':   pd.Series(enorm_hist, index=dti, name='eigen_innov_norm'),",
    "        'rotation_events':    rot_df,",
    "        'dates':              dti,",
    "    }",
    "",
    "",
    "print('Running Kalman filters (Filter A: loadings, Filter B: eigenvalues)...')",
    "kf_result = run_kalman_filters(eigen_result, params, K_max=K_max, sim_threshold=0.5)",
    "",
    "n_dates = len(kf_result['dates'])",
    "n_rot   = len(kf_result['rotation_events'])",
    "print(f'Filter completed: {n_dates} dates')",
    "print(f'Rotation events:  {n_rot} total')",
    "if n_rot > 0:",
    "    print('  Rotation events by factor:')",
    "    for k in range(1, K_max + 1):",
    "        n_k = int((kf_result['rotation_events']['factor_k'] == k).sum())",
    "        print(f'    F{k}: {n_k}')",
    "print('Mean similarity by factor:')",
    "for k, col in enumerate([f'F{j+1}' for j in range(K_max)]):",
    "    mean_s = float(kf_result['similarities'][col].mean())",
    "    print(f'  F{k+1}: {mean_s:.4f}')",
    "print(f'Loading Kalman gain (mean): {kf_result[\"K_gain_v\"].mean().values.round(4)}')",
    "print(f'Eigenvalue Kalman gain (mean): {kf_result[\"K_gain_lam\"].mean().values.round(4)}')",
),

md("## Cell 6 — Contemporaneous factor decomposition"),

# ── Cell 6 ─────────────────────────────────────────────────────────────────
code(
    "def decompose_returns(",
    "    returns: pd.DataFrame,",
    "    kf_result: dict,",
    "    eigen_result: dict,",
    "    K_max: int = 5,",
    ") -> dict:",
    "    \"\"\"",
    "    Project observed returns onto smoothed factor structure.",
    "    Purely contemporaneous — no forecasting.",
    "",
    "    f_tilde_t = pinv(Lambda_bar_t) @ r_t  (OLS on N x K_t Lambda_bar_t)",
    "    e_t       = r_t - Lambda_bar_t @ f_tilde_t  (idiosyncratic residual)",
    "    R²_t      = 1 - ||e_t||² / ||r_t||²",
    "    \"\"\"",
    "    fcols_    = [f'F{k+1}' for k in range(K_max)]",
    "    asset_cols = list(returns.columns)",
    "",
    "    f_tilde_lst = []",
    "    resid_lst   = []",
    "    fc_lst      = []",
    "    r2_lst      = []",
    "    dates_out   = []",
    "",
    "    K_t_ser = eigen_result['K_t']",
    "",
    "    for dt in kf_result['dates']:",
    "        if dt not in returns.index:",
    "            continue",
    "        r_t = returns.loc[dt].values",
    "        if np.any(np.isnan(r_t)):",
    "            continue",
    "",
    "        K_t = int(K_t_ser.loc[dt]) if dt in K_t_ser.index else K_max",
    "        Lam = kf_result['V_bar'][dt][:, :K_t]   # N x K_t (smoothed loadings)",
    "",
    "        # OLS: f_tilde = (Lam.T Lam)^{-1} Lam.T r_t = lstsq(Lam, r_t)",
    "        f_t, _, _, _ = np.linalg.lstsq(Lam, r_t, rcond=None)",
    "",
    "        fc_t  = Lam @ f_t                         # systematic return",
    "        e_t   = r_t - fc_t                         # idiosyncratic",
    "",
    "        denom = float(np.dot(r_t, r_t))",
    "        r2    = 1.0 - float(np.dot(e_t, e_t)) / denom if denom > 1e-10 else 0.0",
    "",
    "        f_full = np.full(K_max, np.nan)",
    "        f_full[:K_t] = f_t",
    "",
    "        f_tilde_lst.append(f_full)",
    "        resid_lst.append(e_t)",
    "        fc_lst.append(fc_t)",
    "        r2_lst.append(r2)",
    "        dates_out.append(dt)",
    "",
    "    dti = pd.DatetimeIndex(dates_out)",
    "    return {",
    "        'f_tilde':       pd.DataFrame(f_tilde_lst, index=dti, columns=fcols_),",
    "        'residual':      pd.DataFrame(resid_lst,   index=dti, columns=asset_cols),",
    "        'factor_contrib': pd.DataFrame(fc_lst,     index=dti, columns=asset_cols),",
    "        'r_squared':     pd.Series(r2_lst,         index=dti, name='r_squared'),",
    "    }",
    "",
    "",
    "decomp = decompose_returns(panel, kf_result, eigen_result, K_max=K_max)",
    "",
    "print(f\"Mean R² (fraction explained by factors): {decomp['r_squared'].mean():.3f}\")",
    "print(f\"Median R²: {decomp['r_squared'].median():.3f}\")",
    "print('R² by turbulence regime:')",
    "reg_ser = turb.regime.reindex(decomp['r_squared'].index, method='ffill')",
    "for regime in ['Calm', 'Elevated', 'Turbulent', 'Crisis']:",
    "    mask = reg_ser == regime",
    "    if mask.sum() < 5:",
    "        continue",
    "    r2_sub = decomp['r_squared'].loc[mask]",
    "    print(f'  {regime:10s}: mean={r2_sub.mean():.3f}  std={r2_sub.std():.3f}  n={mask.sum()}')",
    "print('Expected: higher R² in Turbulent/Crisis (factors dominate idiosyncratic risk).')",
),

md("## Cell 7 — Interpretability analysis (5 plots)"),

# ── Cell 7 ─────────────────────────────────────────────────────────────────
code(
    "REGIME_HEX = {'Calm': '#2ecc71', 'Elevated': '#f39c12',",
    "              'Turbulent': '#e67e22', 'Crisis': '#e74c3c'}",
    "",
    "def _add_regime_shading(fig, regime_s, row=None, col=None):",
    "    reg = regime_s.dropna()",
    "    in_block, x0, prev_r = False, None, None",
    "    for dt, r in reg.items():",
    "        if r != prev_r:",
    "            if in_block and prev_r in REGIME_HEX:",
    "                kw = dict(x0=x0, x1=dt, fillcolor=REGIME_HEX[prev_r], opacity=0.10, line_width=0)",
    "                if row is not None:",
    "                    kw.update(row=row, col=col)",
    "                fig.add_vrect(**kw)",
    "            x0, in_block = dt, True",
    "        prev_r = r",
    "    if in_block and prev_r in REGIME_HEX:",
    "        kw = dict(x0=x0, x1=reg.index[-1], fillcolor=REGIME_HEX[prev_r], opacity=0.10, line_width=0)",
    "        if row is not None:",
    "            kw.update(row=row, col=col)",
    "        fig.add_vrect(**kw)",
    "",
    "dates_kf  = kf_result['dates']",
    "lam_bar_  = kf_result['lam_bar']   # T x K_max ndarray",
    "Kt_kf     = eigen_result['K_t'].reindex(dates_kf, method='nearest')",
    "lnoise_kf = eigen_result['lambda_noise'].reindex(dates_kf, method='nearest')",
    "reg_kf    = turb.regime.reindex(dates_kf, method='ffill')",
    "",
    "# ── Plot A: K_t and eigenvalue evolution ─────────────────────────────",
    "fig_A = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.04,",
    "    row_heights=[0.35, 0.65],",
    "    subplot_titles=['K_t (MP signal factors)', 'Smoothed eigenvalues λ̄_k'])",
    "_add_regime_shading(fig_A, reg_kf, row=1, col=1)",
    "_add_regime_shading(fig_A, reg_kf, row=2, col=1)",
    "",
    "fig_A.add_trace(go.Scatter(x=dates_kf, y=Kt_kf.values, mode='lines', name='K_t',",
    "    line=dict(color='#00d4aa', width=1.5, shape='hv')), row=1, col=1)",
    "fig_A.add_hline(y=2, line_dash='dash', line_color='#2ecc71', line_width=0.7, row=1, col=1)",
    "fig_A.add_hline(y=5, line_dash='dash', line_color='#e74c3c', line_width=0.7, row=1, col=1)",
    "",
    "EV_COLORS = ['#e74c3c','#3498db','#2ecc71','#f39c12','#9b59b6']",
    "for k in range(K_max):",
    "    fig_A.add_trace(go.Scatter(x=dates_kf, y=lam_bar_[:, k], mode='lines',",
    "        name=f'λ̄_F{k+1}', line=dict(color=EV_COLORS[k], width=1.2)), row=2, col=1)",
    "fig_A.add_trace(go.Scatter(x=dates_kf, y=lnoise_kf.values, mode='lines',",
    "    name='λ_noise (MP floor)', line=dict(color='white', width=0.8, dash='dot')), row=2, col=1)",
    "",
    "# Annotate stress episodes",
    "for label, xdate in [('COVID', '2020-03-23'), ('Estallido', '2019-10-25'),",
    "                      ('SVB', '2023-03-13'), ('2022H1', '2022-06-01')]:",
    "    ts_ = pd.Timestamp(xdate)",
    "    if dates_kf[0] <= ts_ <= dates_kf[-1]:",
    "        fig_A.add_vline(x=ts_, line_dash='dot', line_color='white', line_width=0.7, row=1, col=1)",
    "        fig_A.add_annotation(x=ts_, y=5.3, text=label, font=dict(size=9, color='white'),",
    "                              showarrow=False, xref='x', yref='y', row=1, col=1)",
    "",
    "fig_A.update_layout(template='plotly_dark', height=480,",
    "    title='Signal factor count K_t and smoothed eigenvalues',",
    "    margin=dict(l=50,r=40,t=55,b=55),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_A.show()",
    "",
    "# ── Plot B: Smoothed loading evolution ───────────────────────────────",
    "asset_names = list(panel.columns)",
    "fig_B = make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing=0.04,",
    "    subplot_titles=['F1 smoothed loadings', 'F2 smoothed loadings', 'F3 smoothed loadings'])",
    "",
    "for ki in range(3):",
    "    # Mean |loading| per asset for this factor",
    "    mean_abs = np.array([",
    "        np.mean(np.abs([kf_result['V_bar'][d][j, ki] for d in dates_kf]))",
    "        for j in range(N)])",
    "    top3_idx = np.argsort(mean_abs)[::-1][:3]",
    "    line_colors = ['#e74c3c','#3498db','#2ecc71','#f39c12','#9b59b6']",
    "",
    "    for j_rank, j in enumerate(top3_idx):",
    "        load_ts = [np.abs(kf_result['V_bar'][d][j, ki]) for d in dates_kf]",
    "        fig_B.add_trace(go.Scatter(x=dates_kf, y=load_ts, mode='lines',",
    "            name=f'F{ki+1}/{asset_names[j]}',",
    "            line=dict(color=line_colors[j_rank], width=1.2)), row=ki+1, col=1)",
    "",
    "    # Rotation events for this factor",
    "    if len(kf_result['rotation_events']) > 0:",
    "        rot_k = kf_result['rotation_events'][",
    "            kf_result['rotation_events']['factor_k'] == ki + 1]",
    "        for _, row_ in rot_k.iterrows():",
    "            fig_B.add_vline(x=row_['date'], line_dash='dash', line_color='white',",
    "                line_width=0.6, row=ki+1, col=1)",
    "",
    "fig_B.update_layout(template='plotly_dark', height=560,",
    "    title='Factor loading evolution (smoothed) — top 3 assets per factor',",
    "    margin=dict(l=50,r=40,t=55,b=55),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_B.add_annotation(x=0.01, y=-0.07, xref='paper', yref='paper', showarrow=False,",
    "    text='Vertical lines = structural rotation events (similarity < 0.5).',",
    "    font=dict(size=9, color='#aaaaaa'))",
    "fig_B.show()",
    "",
    "# ── Plot C: Factor shocks ─────────────────────────────────────────────",
    "fig_C = make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing=0.04,",
    "    subplot_titles=[f'F{k+1} contemporaneous shock' for k in range(3)])",
    "for k in range(3):",
    "    fk  = f'F{k+1}'",
    "    ft  = decomp['f_tilde'][fk].dropna()",
    "    thr = 2 * ft.std()",
    "    pos = ft.clip(lower=0)",
    "    neg = ft.clip(upper=0)",
    "    fig_C.add_trace(go.Bar(x=ft.index, y=pos.values, name=f'{fk}+',",
    "        marker_color='#3498db', opacity=0.8, showlegend=False), row=k+1, col=1)",
    "    fig_C.add_trace(go.Bar(x=ft.index, y=neg.values, name=f'{fk}-',",
    "        marker_color='#e74c3c', opacity=0.8, showlegend=False), row=k+1, col=1)",
    "    fig_C.add_hline(y=float(thr),  line_dash='dash', line_color='#f39c12', line_width=0.8, row=k+1, col=1)",
    "    fig_C.add_hline(y=float(-thr), line_dash='dash', line_color='#f39c12', line_width=0.8, row=k+1, col=1)",
    "fig_C.update_layout(template='plotly_dark', height=540, barmode='overlay',",
    "    title='Contemporaneous factor shocks f̃_k_t',",
    "    margin=dict(l=50,r=40,t=55,b=55),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_C.add_annotation(x=0.01, y=-0.07, xref='paper', yref='paper', showarrow=False,",
    "    text='Daily OLS projection of returns onto smoothed factor structure. Not a prediction.',",
    "    font=dict(size=9, color='#aaaaaa'))",
    "fig_C.show()",
    "",
    "# ── Plot D: Innovation signals ────────────────────────────────────────",
    "ln_ser = kf_result['loading_innov_norm'].iloc[1:]   # skip initialization",
    "en_ser = kf_result['eigen_innov_norm'].iloc[1:]",
    "thr_ln = ln_ser.mean() + 2 * ln_ser.std()",
    "thr_en = en_ser.mean() + 2 * en_ser.std()",
    "",
    "fig_D = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.05,",
    "    subplot_titles=['Loading innovation ||ΔΛ||_F', 'Eigenvalue innovation ||Δλ||'])",
    "for ser_, thr_, col_, row_, lbl_ in [",
    "        (ln_ser, thr_ln, '#3498db', 1, 'loading'),",
    "        (en_ser, thr_en, '#e74c3c', 2, 'eigenvalue')]:",
    "    fig_D.add_trace(go.Scatter(x=ser_.index, y=ser_.values, mode='lines',",
    "        name=lbl_, line=dict(color=col_, width=0.9)), row=row_, col=1)",
    "    above = ser_[ser_ > thr_]",
    "    fig_D.add_trace(go.Scatter(x=above.index, y=above.values, mode='markers',",
    "        marker=dict(color='white', size=3), showlegend=False), row=row_, col=1)",
    "    fig_D.add_hline(y=float(thr_), line_dash='dash', line_color='#f39c12', line_width=0.8, row=row_, col=1)",
    "    top5 = ser_.nlargest(5)",
    "    for dt_, val_ in top5.items():",
    "        fig_D.add_annotation(x=dt_, y=val_, text=str(dt_.date()),",
    "            font=dict(size=8, color='#f39c12'), showarrow=True, arrowwidth=0.5,",
    "            arrowcolor='#f39c12', ax=0, ay=-20, row=row_, col=1)",
    "",
    "fig_D.update_layout(template='plotly_dark', height=440,",
    "    title='Kalman filter innovation signals: structural break detection',",
    "    margin=dict(l=50,r=40,t=55,b=60),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_D.add_annotation(x=0.01, y=-0.10, xref='paper', yref='paper', showarrow=False,",
    "    text='Loading innovation = unexpected shift in factor direction. Eigenvalue innovation = unexpected change in factor variance.',",
    "    font=dict(size=9, color='#aaaaaa'))",
    "fig_D.show()",
    "",
    "# ── Plot E: Return decomposition ─────────────────────────────────────",
    "sel_assets = ['BRL', 'BRA', 'CLP']",
    "fig_E = make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing=0.05,",
    "    subplot_titles=[f'{a} return decomposition (monthly)' for a in sel_assets])",
    "FACTOR_COLORS = ['#e74c3c','#3498db','#2ecc71','#f39c12','#9b59b6']",
    "",
    "for i, asset in enumerate(sel_assets):",
    "    if asset not in panel.columns:",
    "        continue",
    "    asset_idx = list(panel.columns).index(asset)",
    "",
    "    # Per-factor contribution to this asset",
    "    k_max_use = min(3, K_max)  # show top 3 factors for clarity",
    "    stacked = {}",
    "    for k in range(k_max_use):",
    "        fk = f'F{k+1}'",
    "        contrib_k = pd.Series({",
    "            dt: kf_result['V_bar'][dt][asset_idx, k] * float(decomp['f_tilde'].loc[dt, fk])",
    "            for dt in decomp['f_tilde'].index",
    "            if not np.isnan(decomp['f_tilde'].loc[dt, fk])},",
    "            name=fk)",
    "        stacked[fk] = contrib_k.resample('ME').sum()",
    "",
    "    r_monthly   = panel[asset].resample('ME').sum()",
    "    idx_monthly = list(stacked.values())[0].index",
    "",
    "    for k in range(k_max_use):",
    "        fk  = f'F{k+1}'",
    "        fig_E.add_trace(go.Bar(x=idx_monthly, y=stacked[fk].reindex(idx_monthly).values,",
    "            name=f'{asset}/{fk}', marker_color=FACTOR_COLORS[k], opacity=0.85),",
    "            row=i+1, col=1)",
    "",
    "    fig_E.add_trace(go.Scatter(x=r_monthly.index, y=r_monthly.values, mode='lines',",
    "        name=f'{asset} total', line=dict(color='white', width=1.0, dash='dot')),",
    "        row=i+1, col=1)",
    "",
    "fig_E.update_layout(template='plotly_dark', height=600, barmode='relative',",
    "    title='Return decomposition: factor attribution (monthly)',",
    "    margin=dict(l=50,r=40,t=55,b=70),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_E.add_annotation(x=0.01, y=-0.09, xref='paper', yref='paper', showarrow=False,",
    "    text='Systematic = Λ̄_t f̃_t per factor. White dashed = actual monthly return.',",
    "    font=dict(size=9, color='#aaaaaa'))",
    "fig_E.show()",
),

md("## Cell 8 — Empirical validation"),

# ── Cell 8 ─────────────────────────────────────────────────────────────────
code(
    "# ── Test 1: Do innovation signals lead tau? ───────────────────────────",
    "tau_ser   = turb.turbulence.dropna()",
    "ln_sig    = kf_result['loading_innov_norm'].iloc[1:].dropna()",
    "en_sig    = kf_result['eigen_innov_norm'].iloc[1:].dropna()",
    "",
    "def _xcorr_series(x_ser, y_ser, lags):",
    "    common = x_ser.index.intersection(y_ser.index)",
    "    x_arr  = x_ser.reindex(common).values",
    "    y_arr  = y_ser.reindex(common).values",
    "    xcorrs = []",
    "    for lag in lags:",
    "        if lag < 0:",
    "            xi, yi = x_arr[:lag], y_arr[-lag:]",
    "        elif lag > 0:",
    "            xi, yi = x_arr[lag:], y_arr[:-lag]",
    "        else:",
    "            xi, yi = x_arr, y_arr",
    "        xcorrs.append(np.corrcoef(xi, yi)[0, 1] if len(xi) > 10 else np.nan)",
    "    return np.array(xcorrs)",
    "",
    "lags      = list(range(-15, 16))",
    "xcorr_ln  = _xcorr_series(ln_sig, tau_ser, lags)",
    "xcorr_en  = _xcorr_series(en_sig, tau_ser, lags)",
    "",
    "lag_v   = lags[int(np.nanargmax(np.abs(xcorr_ln)))]",
    "lag_lam = lags[int(np.nanargmax(np.abs(xcorr_en)))]",
    "r_v_peak  = xcorr_ln[int(np.nanargmax(np.abs(xcorr_ln)))]",
    "r_lam_peak = xcorr_en[int(np.nanargmax(np.abs(xcorr_en)))]",
    "",
    "fig_xcorr = go.Figure()",
    "fig_xcorr.add_bar(x=lags, y=xcorr_ln.tolist(), name='Loading innov vs tau',",
    "    marker_color=['#3498db' if v >= 0 else '#e74c3c' for v in xcorr_ln.tolist()])",
    "fig_xcorr.add_trace(go.Scatter(x=lags, y=xcorr_en.tolist(), mode='lines+markers',",
    "    name='Eigenvalue innov vs tau', line=dict(color='#f39c12', width=1.5)))",
    "fig_xcorr.add_vline(x=0, line_dash='dash', line_color='white', line_width=0.8)",
    "fig_xcorr.update_layout(template='plotly_dark', height=320,",
    "    title='Cross-correlation: DFM innovation signals vs turbulence tau',",
    "    xaxis_title='Lag (days; negative = innovation LEADS tau)',",
    "    yaxis_title='Pearson r',",
    "    margin=dict(l=50,r=40,t=50,b=50),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_xcorr.show()",
    "",
    "print(f'Loading innovation peak lag:   lag={lag_v:+d}d  r={r_v_peak:.3f}')",
    "print(f'Eigenvalue innovation peak lag: lag={lag_lam:+d}d  r={r_lam_peak:.3f}')",
    "for lag_, name_ in [(lag_v,'Loading'), (lag_lam,'Eigenvalue')]:",
    "    if lag_ < 0:",
    "        print(f'  {name_} innovation LEADS tau by {-lag_} days (early warning)')",
    "    elif lag_ > 0:",
    "        print(f'  {name_} innovation LAGS tau by {lag_} days (reactive)')",
    "    else:",
    "        print(f'  {name_} innovation is contemporaneous with tau')",
    "",
    "# ── Test 2: R² by turbulence regime ──────────────────────────────────",
    "r2_ser = decomp['r_squared']",
    "reg_r2 = turb.regime.reindex(r2_ser.index, method='ffill')",
    "print('\\nR² by turbulence regime:')",
    "print(f'  {\"Regime\":<12} {\"N\":>5} {\"Mean R²\":>9} {\"Std R²\":>9} {\"Min R²\":>9} {\"Max R²\":>9}')",
    "r2_by_regime = {}",
    "for regime in ['Calm', 'Elevated', 'Turbulent', 'Crisis']:",
    "    mask = reg_r2 == regime",
    "    if mask.sum() < 5:",
    "        continue",
    "    sub = r2_ser[mask]",
    "    r2_by_regime[regime] = sub",
    "    print(f'  {regime:<12} {mask.sum():>5} {sub.mean():>9.3f} {sub.std():>9.3f} '",
    "          f'{sub.min():>9.3f} {sub.max():>9.3f}')",
    "",
    "if 'Calm' in r2_by_regime and 'Crisis' in r2_by_regime:",
    "    from scipy.stats import ttest_ind",
    "    t_stat, p_val = ttest_ind(r2_by_regime['Crisis'], r2_by_regime['Calm'],",
    "                               alternative='greater')",
    "    print(f'  t-test Crisis > Calm: t={t_stat:.3f}  p={p_val:.4f}')",
    "    if p_val < 0.05:",
    "        print('  -> Crisis R² is significantly higher than Calm R² (p<0.05)')",
    "",
    "# ── Test 3: Similarity scores and structural change ───────────────────",
    "sim_mean = kf_result['similarities'].mean(axis=1)   # mean across K_max factors",
    "sim_low   = (sim_mean < 0.7)                         # low similarity periods",
    "tau_at_sim = turb.regime.reindex(sim_mean.index, method='ffill')",
    "",
    "xcorr_sim = _xcorr_series(1.0 - sim_mean, tau_ser, lags)   # low sim = high (1-sim)",
    "lag_sim   = lags[int(np.nanargmax(np.abs(xcorr_sim)))]",
    "",
    "fig_sim = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.05,",
    "    subplot_titles=['Mean factor similarity (across K_t factors)', 'Cross-corr (1-sim) vs tau'])",
    "fig_sim.add_trace(go.Scatter(x=sim_mean.index, y=sim_mean.values, mode='lines',",
    "    name='mean sim', line=dict(color='#00d4aa', width=0.9)), row=1, col=1)",
    "fig_sim.add_hline(y=0.7, line_dash='dash', line_color='#f39c12', line_width=0.8, row=1, col=1)",
    "fig_sim.add_bar(x=lags, y=xcorr_sim.tolist(), name='(1-sim) vs tau', row=2, col=1,",
    "    marker_color=['#3498db' if v >= 0 else '#e74c3c' for v in xcorr_sim.tolist()])",
    "fig_sim.add_vline(x=0, line_dash='dash', line_color='white', line_width=0.8, row=2, col=1)",
    "fig_sim.update_layout(template='plotly_dark', height=400,",
    "    title='Factor similarity vs turbulence tau',",
    "    margin=dict(l=50,r=40,t=50,b=50),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_sim.show()",
    "",
    "for regime in ['Calm', 'Elevated', 'Turbulent', 'Crisis']:",
    "    regime_mask = tau_at_sim == regime",
    "    pct = 100 * float(sim_low[regime_mask].sum()) / float(sim_low.sum()) if sim_low.sum() > 0 else 0.0",
    "    print(f'  Low-similarity periods in {regime:10s}: {pct:.1f}% of all low-sim dates')",
    "",
    "# ── Test 4: Rotation event calendar ──────────────────────────────────",
    "rot_df = kf_result['rotation_events'].copy()",
    "if len(rot_df) > 0:",
    "    rot_df['regime'] = [str(turb.regime.reindex([d], method='ffill').iloc[0])",
    "                         for d in rot_df['date']]",
    "    tau_pct_list = []",
    "    tau_all_vals = turb.turbulence.dropna().values",
    "    for d in rot_df['date']:",
    "        if d in turb.turbulence.index:",
    "            tv = float(turb.turbulence.loc[d])",
    "            pct_ = float(sp_stats.percentileofscore(tau_all_vals, tv))",
    "        else:",
    "            pct_ = float('nan')",
    "        tau_pct_list.append(round(pct_, 1))",
    "    rot_df['tau_pctile'] = tau_pct_list",
    "    rot_sorted = rot_df.sort_values('similarity').head(20)",
    "    print('\\nTop 20 rotation events (most extreme first):')",
    "    print(rot_sorted.to_string(index=False))",
    "    crisis_rot = (rot_df['regime'] == 'Crisis').sum()",
    "    print(f'\\nRotation events during Crisis regime: {crisis_rot} / {len(rot_df)} = {100*crisis_rot/len(rot_df):.1f}%')",
    "else:",
    "    print('No rotation events detected at sim_threshold=0.5.')",
),

md("## Cell 9 — Factor interpretation narrative"),

# ── Cell 9 ─────────────────────────────────────────────────────────────────
code(
    "ev_df   = pd.DataFrame(kf_result['lam_bar'], index=kf_result['dates'],",
    "                       columns=[f'F{k+1}' for k in range(K_max)])",
    "f_tilde = decomp['f_tilde']",
    "Kt_kf2  = eigen_result['K_t'].reindex(kf_result['dates'], method='nearest')",
    "",
    "periods = {",
    "    'normal_2018':  ('2018-01-01', '2018-12-31'),",
    "    'covid':        ('2020-02-20', '2020-04-30'),",
    "    'estallido':    ('2019-10-01', '2019-11-30'),",
    "}",
    "",
    "print('=' * 60)",
    "print('DYNAMIC FACTOR MODEL v2: FACTOR INTERPRETATION')",
    "print('=' * 60)",
    "",
    "for k in range(K_max):",
    "    fk = f'F{k+1}'",
    "    # Mean share of total variance (smoothed eigenvalue ratio)",
    "    lam_sum = ev_df.sum(axis=1).replace(0, np.nan)",
    "    share   = (ev_df[fk] / lam_sum).dropna()",
    "    mean_exp = float(share.mean())",
    "",
    "    # Top loading assets",
    "    mean_abs = {asset_names[j]: np.mean(np.abs([kf_result['V_bar'][d][j, k]",
    "               for d in kf_result['dates']])) for j in range(N)}",
    "    top3_ = sorted(mean_abs, key=mean_abs.get, reverse=True)[:3]",
    "",
    "    print(f'\\nF{k+1} — mean share of total variance: {mean_exp:.1%}')",
    "    print(f'  Top loading assets: {top3_}')",
    "    for pname, (ps, pe) in periods.items():",
    "        ts_ = pd.Timestamp(ps); te_ = pd.Timestamp(pe)",
    "        sub = f_tilde.loc[(f_tilde.index >= ts_) & (f_tilde.index <= te_), fk].dropna()",
    "        if len(sub) > 0:",
    "            print(f'  {pname:15s}: mean={sub.mean():.4f}  std={sub.std():.4f}')",
    "    n_rot_k = int((kf_result['rotation_events']['factor_k'] == k + 1).sum())",
    "    print(f'  Rotation events: {n_rot_k}')",
    "    print(f'  Interpretation: [FILL IN MANUALLY after inspection]')",
    "",
    "print()",
    "print('SYSTEM-LEVEL PROPERTIES:')",
    "K_t_mean = float(Kt_kf2.mean())",
    "r2_mean  = float(decomp['r_squared'].mean())",
    "r2_cr    = float(r2_by_regime.get('Crisis', pd.Series([np.nan])).mean())",
    "print(f'  Mean K_t: {K_t_mean:.2f}')",
    "for pname, (ps, pe) in periods.items():",
    "    ts_ = pd.Timestamp(ps); te_ = pd.Timestamp(pe)",
    "    sub = Kt_kf2.loc[(Kt_kf2.index >= ts_) & (Kt_kf2.index <= te_)]",
    "    if len(sub) > 0:",
    "        print(f'  K_t during {pname}: mean={sub.mean():.2f}  peak={int(sub.max())}')",
    "print(f'  Mean R² (factor model fit): {r2_mean:.3f}')",
    "print(f'  R² during Crisis: {r2_cr:.3f}')",
    "print(f'  Total rotation events: {len(kf_result[\"rotation_events\"])}')",
    "print(f'  Loading innovation lead over tau: lag={lag_v:+d} days')",
    "print(f'  Eigenvalue innovation lead over tau: lag={lag_lam:+d} days')",
),

md("## Cell 10 — Save results"),

# ── Cell 10 ────────────────────────────────────────────────────────────────
code(
    "import pickle",
    "",
    "# ── Save calibrated parameters ────────────────────────────────────────",
    "os.makedirs('../data/_cache', exist_ok=True)",
    "params_save = {",
    "    'q_v':        params['q_v'],",
    "    'r_v':        params['r_v'],",
    "    'phi':        params['phi'],",
    "    'q_lambda':   params['q_lambda'],",
    "    'r_lambda':   params['r_lambda'],",
    "    'K_min': 2, 'K_max': 5,",
    "    'lam_ewma':   0.94,",
    "    'window':     252,",
    "    'sim_threshold': 0.5,",
    "    'trained_on': '2015-2019',",
    "    'asset_names': list(panel.columns),",
    "    'N': N,",
    "}",
    "with open('../data/_cache/dfm_params_v2.pkl', 'wb') as fh:",
    "    pickle.dump(params_save, fh)",
    "print('Saved: data/_cache/dfm_params_v2.pkl')",
    "",
    "# ── Export to Excel ───────────────────────────────────────────────────",
    "os.makedirs('../exports', exist_ok=True)",
    "fname = f'../exports/dfm_v2_results_{date.today()}.xlsx'",
    "",
    "with pd.ExcelWriter(fname, engine='openpyxl') as writer:",
    "    # Smoothed loadings: one sheet per factor",
    "    for k in range(K_max):",
    "        df_lk = pd.DataFrame(",
    "            {asset: [kf_result['V_bar'][d][ai, k] for d in kf_result['dates']]",
    "             for ai, asset in enumerate(panel.columns)},",
    "            index=kf_result['dates'])",
    "        df_lk.to_excel(writer, sheet_name=f'Loading_F{k+1}')",
    "",
    "    # Smoothed eigenvalues",
    "    pd.DataFrame(kf_result['lam_bar'], index=kf_result['dates'],",
    "                 columns=[f'F{k+1}' for k in range(K_max)]",
    "    ).to_excel(writer, sheet_name='Eigenvalues_smoothed')",
    "",
    "    # Raw vs smoothed comparison",
    "    pd.DataFrame({",
    "        **{f'raw_F{k+1}':    [eigen_result['lambda_hat'][d][k] for d in kf_result['dates']]",
    "           for k in range(K_max)},",
    "        **{f'smooth_F{k+1}': kf_result['lam_bar'][:, k].tolist()",
    "           for k in range(K_max)},",
    "    }, index=kf_result['dates']).to_excel(writer, sheet_name='Eigenvalues_raw_vs_smooth')",
    "",
    "    # Factor shocks",
    "    decomp['f_tilde'].to_excel(writer, sheet_name='Factor_shocks')",
    "",
    "    # Return decomposition",
    "    decomp['factor_contrib'].to_excel(writer, sheet_name='Factor_attribution')",
    "    decomp['residual'].to_excel(writer,        sheet_name='Idiosyncratic')",
    "    decomp['r_squared'].to_frame('R2').to_excel(writer, sheet_name='R_squared')",
    "",
    "    # Innovation signals",
    "    pd.DataFrame({",
    "        'loading_innov_norm': kf_result['loading_innov_norm'],",
    "        'eigen_innov_norm':   kf_result['eigen_innov_norm'],",
    "    }).to_excel(writer, sheet_name='Innovation_signals')",
    "",
    "    # Rotation events",
    "    kf_result['rotation_events'].to_excel(writer, sheet_name='Rotation_events', index=False)",
    "",
    "    # K_t and MP diagnostics",
    "    pd.DataFrame({",
    "        'K_t':          eigen_result['K_t'],",
    "        'lambda_plus':  eigen_result['lambda_plus'],",
    "        'lambda_noise': eigen_result['lambda_noise'],",
    "    }).to_excel(writer, sheet_name='MP_diagnostics')",
    "",
    "print(f'Saved: {fname}')",
),

])  # end save()

print("Done.")
