"""
Generator for notebooks/06_dynamic_factor_model.ipynb
Run from em_risk_dashboard/ directory.
"""
import json, pathlib, uuid

NB_DIR = pathlib.Path("notebooks")
NB_DIR.mkdir(exist_ok=True)


def new_id():
    return uuid.uuid4().hex[:8]

def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12.0"},
        },
        "cells": cells,
    }

def md(*lines):
    return {"id": new_id(), "cell_type": "markdown", "metadata": {},
            "source": [l + "\n" for l in lines]}

def code(*lines):
    return {"id": new_id(), "cell_type": "code", "execution_count": None,
            "metadata": {}, "outputs": [],
            "source": [l + "\n" for l in lines]}

def save(name, cells):
    path = NB_DIR / name
    with open(path, "w") as f:
        json.dump(nb(cells), f, indent=1)
    print(f"  wrote {path}")


save("06_dynamic_factor_model.ipynb", [

md(
    "# 06 · Dynamic Factor Model (Kalman + Marchenko-Pastur)",
    "",
    "**Prototype validation notebook.** Not yet wired into modules/.",
    "",
    "Model separates the return panel into:",
    "- **Signal factors** (K_t, MP-threshold): latent states via Kalman filter",
    "- **Noise factors** (sub-MP): aggregated into scalar noise floor λ_noise → H_t = λ_noise · I_N",
    "",
    "State space:",
    "```",
    "  f_t = f_{t-1} + η_t,       η_t ~ N(0, Q)          [random walk]",
    "  r_t = Λ_t @ f_t + ε_t,     ε_t ~ N(0, H_t)        [observation]",
    "```",
    "Q calibrated via MLE on 2015–2019 training window (K_max parameters only).",
    "H_t set analytically from MP noise floor — NOT estimated.",
),

# ── Cell 1 — Setup ─────────────────────────────────────────────────────────
code(
    "import sys, os",
    "sys.path.insert(0, os.path.join(os.getcwd(), '..'))",
    "import warnings; warnings.filterwarnings('ignore')",
    "",
    "import numpy as np",
    "import pandas as pd",
    "from scipy import optimize, linalg, stats as sp_stats",
    "import plotly.graph_objects as go",
    "from plotly.subplots import make_subplots",
    "from datetime import date",
    "",
    "from data.fetcher import load_em_universe",
    "from core.returns import log_returns",
    "from modules.turbulence import compute_turbulence_index",
    "",
    "# ── Load data ────────────────────────────────────────────────────────",
    "raw   = load_em_universe(start='2015-01-01', use_cache=True)",
    "fx    = log_returns(raw['fx'])",
    "eq    = log_returns(raw['equity'])",
    "eq.columns = ['CHL', 'BRA', 'MEX', 'COL', 'PER']",
    "gl    = log_returns(raw['global'])",
    "panel = pd.concat([fx, eq, gl], axis=1).dropna(how='all')",
    "N     = panel.shape[1]",
    "print(f'Panel: {panel.shape} | Assets: {list(panel.columns)}')",
    "",
    "# ── Turbulence for regime shading ─────────────────────────────────────",
    "kw   = dict(window=252, min_periods=60, vol_standardize=True, slow_window=504)",
    "turb = compute_turbulence_index(panel, **kw)",
    "print('Turbulence computed.')",
),

md("## Cell 2 — Marchenko-Pastur threshold and dynamic K"),

# ── Cell 2 ─────────────────────────────────────────────────────────────────
code(
    "def marchenko_pastur_threshold(",
    "    eigenvalues: np.ndarray,",
    "    N: int,",
    "    T: int,",
    ") -> tuple:",
    "    \"\"\"",
    "    Compute MP upper bound and count signal factors.",
    "",
    "    Parameters",
    "    ----------",
    "    eigenvalues : sorted descending eigenvalues of sample cov",
    "    N           : number of assets",
    "    T           : window length (observations)",
    "",
    "    Returns",
    "    -------",
    "    lambda_plus  : MP upper bound",
    "    lambda_noise : mean sub-threshold eigenvalues (noise floor)",
    "    K            : number of signal factors, bounded [2, 5]",
    "    \"\"\"",
    "    gamma       = N / T",
    "    sigma2      = np.median(eigenvalues)          # robust noise variance",
    "    lambda_plus = sigma2 * (1 + np.sqrt(gamma))**2",
    "",
    "    K_raw = int(np.sum(eigenvalues > lambda_plus))",
    "    K     = max(2, min(5, K_raw))",
    "",
    "    noise_eigs   = eigenvalues[K:]",
    "    lambda_noise = float(np.mean(noise_eigs)) if len(noise_eigs) > 0 else float(sigma2)",
    "",
    "    return lambda_plus, lambda_noise, K",
    "",
    "",
    "def compute_rolling_loadings(",
    "    returns: pd.DataFrame,",
    "    window: int = 252,",
    "    K_min: int = 2,",
    "    K_max: int = 5,",
    "    lam_smooth: float = 0.97,",
    "    min_periods: int = 60,",
    ") -> dict:",
    "    \"\"\"",
    "    Rolling PCA loadings with MP-based dynamic K and EWMA smoothing.",
    "",
    "    At each date t:",
    "      1. Trailing window -> sample cov -> eigendecompose (descending)",
    "      2. MP threshold -> K_t, lambda_noise_t",
    "      3. Extract top K_max eigenvectors (N x K_max)",
    "      4. Sign-normalize: largest |loading| per column is positive",
    "      5. EWMA-smooth full (N x K_max) loading matrix",
    "      6. Re-normalize each column to unit length",
    "",
    "    Returns dict with keys:",
    "      loadings, raw_loadings, K_t, lambda_noise, lambda_plus,",
    "      explained_var, eigenvalues, asset_names, K_max",
    "    \"\"\"",
    "    dates    = returns.index",
    "    n_assets = returns.shape[1]",
    "    cols     = list(returns.columns)",
    "",
    "    loadings_d      = {}",
    "    raw_loadings_d  = {}",
    "    K_t_d           = {}",
    "    lnoise_d        = {}",
    "    lplus_d         = {}",
    "    ev_rows         = {}",
    "    eig_rows        = {}",
    "    Lambda_smooth   = None",
    "",
    "    arr = returns.values  # T x N",
    "",
    "    for i, dt in enumerate(dates):",
    "        if i < min_periods - 1:",
    "            continue",
    "        i0   = max(0, i - window + 1)",
    "        win  = arr[i0 : i + 1]  # shape (T_win, N)",
    "        T_win = win.shape[0]",
    "",
    "        # fill NaN with column mean for this window",
    "        win_clean = win.copy()",
    "        col_means = np.nanmean(win_clean, axis=0)",
    "        for c in range(n_assets):",
    "            mask = np.isnan(win_clean[:, c])",
    "            win_clean[mask, c] = col_means[c]",
    "",
    "        cov = np.cov(win_clean, rowvar=False)  # N x N",
    "",
    "        # Eigendecompose, sort descending",
    "        eigvals, eigvecs = np.linalg.eigh(cov)",
    "        idx    = np.argsort(eigvals)[::-1]",
    "        eigvals = eigvals[idx]",
    "        eigvecs = eigvecs[:, idx]  # N x N",
    "",
    "        lambda_plus, lambda_noise, K_t = marchenko_pastur_threshold(",
    "            eigvals, n_assets, T_win",
    "        )",
    "",
    "        # Top K_max eigenvectors (N x K_max)",
    "        Lam_raw = eigvecs[:, :K_max].copy()",
    "",
    "        # Sign normalize: largest |loading| per column is positive",
    "        for k in range(K_max):",
    "            if Lam_raw[np.argmax(np.abs(Lam_raw[:, k])), k] < 0:",
    "                Lam_raw[:, k] *= -1",
    "",
    "        # EWMA smoothing",
    "        if Lambda_smooth is None:",
    "            Lambda_smooth = Lam_raw.copy()",
    "        else:",
    "            Lambda_smooth = (1 - lam_smooth) * Lam_raw + lam_smooth * Lambda_smooth",
    "",
    "        # Re-normalize each column to unit length",
    "        Lam_norm = Lambda_smooth.copy()",
    "        for k in range(K_max):",
    "            nrm = np.linalg.norm(Lam_norm[:, k])",
    "            if nrm > 1e-10:",
    "                Lam_norm[:, k] /= nrm",
    "",
    "        loadings_d[dt]     = Lam_norm",
    "        raw_loadings_d[dt] = Lam_raw",
    "        K_t_d[dt]          = K_t",
    "        lnoise_d[dt]       = lambda_noise",
    "        lplus_d[dt]        = lambda_plus",
    "",
    "        top_ev = eigvals[:K_max]",
    "        total  = eigvals.sum()",
    "        ev_rows[dt] = top_ev / total if total > 0 else top_ev * 0",
    "        eig_rows[dt] = top_ev",
    "",
    "    K_t_ser    = pd.Series(K_t_d,      name='K_t').rename_axis('date')",
    "    lnoise_ser = pd.Series(lnoise_d,   name='lambda_noise').rename_axis('date')",
    "    lplus_ser  = pd.Series(lplus_d,    name='lambda_plus').rename_axis('date')",
    "    fcols      = [f'F{k+1}' for k in range(K_max)]",
    "    ev_df      = pd.DataFrame(ev_rows,  index=fcols).T.rename_axis('date')",
    "    eig_df     = pd.DataFrame(eig_rows, index=fcols).T.rename_axis('date')",
    "",
    "    return {",
    "        'loadings':      loadings_d,",
    "        'raw_loadings':  raw_loadings_d,",
    "        'K_t':           K_t_ser,",
    "        'lambda_noise':  lnoise_ser,",
    "        'lambda_plus':   lplus_ser,",
    "        'explained_var': ev_df,",
    "        'eigenvalues':   eig_df,",
    "        'asset_names':   list(returns.columns),",
    "        'K_max':         K_max,",
    "    }",
    "",
    "",
    "# ── Run on full panel ─────────────────────────────────────────────────",
    "print('Computing rolling loadings (window=252)...')",
    "loadings_result = compute_rolling_loadings(panel, window=252)",
    "K_max = loadings_result['K_max']",
    "",
    "print(f\"K_t range: {loadings_result['K_t'].min()} to {loadings_result['K_t'].max()}\")",
    "print(f\"K_t mean:  {loadings_result['K_t'].mean():.2f}\")",
    "print(f\"MP noise floor range: {loadings_result['lambda_noise'].min():.6f}\"",
    "      f\" to {loadings_result['lambda_noise'].max():.6f}\")",
    "",
    "# ── Show loadings at key dates ────────────────────────────────────────",
    "dates_to_show = ['2018-01-02', '2020-03-20', '2024-12-31']",
    "lkeys = sorted(loadings_result['loadings'].keys())",
    "for ds in dates_to_show:",
    "    ts = pd.Timestamp(ds)",
    "    # find nearest available date",
    "    nearest = min(lkeys, key=lambda d: abs((d - ts).days))",
    "    K_at = int(loadings_result['K_t'].loc[nearest])",
    "    Lam  = loadings_result['loadings'][nearest][:, :K_at]",
    "    df_lam = pd.DataFrame(",
    "        Lam,",
    "        index=loadings_result['asset_names'],",
    "        columns=[f'F{k+1}' for k in range(K_at)]",
    "    ).round(3)",
    "    print(f'\\nLoadings at {nearest.date()} (K_t={K_at}):')",
    "    print(df_lam.to_string())",
    "",
    "# ── Plot K_t with regime shading ─────────────────────────────────────",
    "REGIME_HEX = {'Calm':'#2ecc71','Elevated':'#f39c12','Turbulent':'#e67e22','Crisis':'#e74c3c'}",
    "Kt = loadings_result['K_t']",
    "reg = turb.regime.reindex(Kt.index, method='ffill')",
    "",
    "fig_kt = go.Figure()",
    "# Regime shading",
    "in_block, x0, prev_r = False, None, None",
    "for dt, r in reg.items():",
    "    if r != prev_r:",
    "        if in_block and prev_r in REGIME_HEX:",
    "            fig_kt.add_vrect(x0=x0, x1=dt, fillcolor=REGIME_HEX[prev_r], opacity=0.12, line_width=0)",
    "        x0, in_block = dt, True",
    "    prev_r = r",
    "if in_block and prev_r in REGIME_HEX:",
    "    fig_kt.add_vrect(x0=x0, x1=Kt.index[-1], fillcolor=REGIME_HEX[prev_r], opacity=0.12, line_width=0)",
    "",
    "fig_kt.add_trace(go.Scatter(x=Kt.index, y=Kt.values, mode='lines',",
    "    name='K_t', line=dict(color='#00d4aa', width=1.5, shape='hv')))",
    "fig_kt.add_hline(y=2, line_dash='dash', line_color='#2ecc71', line_width=0.8,",
    "    annotation_text='K_min=2', annotation_position='bottom right')",
    "fig_kt.add_hline(y=5, line_dash='dash', line_color='#e74c3c', line_width=0.8,",
    "    annotation_text='K_max=5', annotation_position='top right')",
    "fig_kt.update_layout(",
    "    template='plotly_dark', height=300,",
    "    title='Number of signal factors K_t (Marchenko-Pastur threshold)',",
    "    yaxis=dict(title='K_t', tickvals=[2,3,4,5]),",
    "    margin=dict(l=40,r=40,t=50,b=60),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117'",
    ")",
    "fig_kt.add_annotation(",
    "    x=0.01, y=-0.18, xref='paper', yref='paper', showarrow=False,",
    "    text='Rising K_t = variance concentrating into fewer independent factors = systemic stress signal.',",
    "    font=dict(size=10, color='#aaaaaa'), align='left'",
    ")",
    "fig_kt.show()",
),

md("## Cell 3 — MLE calibration of Q (state noise)"),

# ── Cell 3 ─────────────────────────────────────────────────────────────────
code(
    "def kalman_log_likelihood(",
    "    log_q_diag: np.ndarray,",
    "    returns: pd.DataFrame,",
    "    loadings_result: dict,",
    "    K_max: int,",
    ") -> float:",
    "    \"\"\"",
    "    Negative log-likelihood for MLE of Q diagonal.",
    "",
    "    log_q_diag : log(diagonal of Q), shape (K_max,)",
    "    Returns negative sum of log-likelihood (scalar).",
    "    Large penalty (1e10) on numerical failure.",
    "    \"\"\"",
    "    Q = np.diag(np.exp(log_q_diag))   # K_max x K_max",
    "    A = np.eye(K_max)                  # random walk",
    "",
    "    f     = np.zeros(K_max)            # f_{0|0}",
    "    P     = np.eye(K_max) * 1.0        # P_{0|0}",
    "    ll    = 0.0",
    "    N_obs = returns.shape[1]",
    "    LOG2PI = N_obs * np.log(2.0 * np.pi)",
    "",
    "    dates = sorted(loadings_result['loadings'].keys())",
    "",
    "    for t_date in dates:",
    "        if t_date not in returns.index:",
    "            continue",
    "        r_t = returns.loc[t_date].values",
    "        if np.any(np.isnan(r_t)):",
    "            continue",
    "",
    "        Lambda_t = loadings_result['loadings'][t_date]  # N x K_max",
    "        K_t      = int(loadings_result['K_t'].loc[t_date])",
    "        Lam = Lambda_t[:, :K_t]        # N x K_t",
    "        f_k = f[:K_t]",
    "        P_k = P[:K_t, :K_t]",
    "        Q_k = Q[:K_t, :K_t]",
    "        A_k = A[:K_t, :K_t]",
    "",
    "        lnoise  = float(loadings_result['lambda_noise'].loc[t_date])",
    "        H_t     = lnoise * np.eye(N_obs)",
    "",
    "        # Predict",
    "        f_pred = A_k @ f_k",
    "        P_pred = A_k @ P_k @ A_k.T + Q_k",
    "",
    "        # Innovation",
    "        e_t = r_t - Lam @ f_pred",
    "        S_t = Lam @ P_pred @ Lam.T + H_t",
    "",
    "        sign, logdet = np.linalg.slogdet(S_t)",
    "        if sign <= 0:",
    "            return 1e10",
    "        try:",
    "            S_inv  = np.linalg.solve(S_t, np.eye(N_obs))",
    "            mahal  = float(e_t @ S_inv @ e_t)",
    "        except np.linalg.LinAlgError:",
    "            return 1e10",
    "",
    "        ll += -0.5 * (logdet + mahal + LOG2PI)",
    "",
    "        # Update (only K_t active block)",
    "        K_gain  = P_pred @ Lam.T @ S_inv",
    "        f_new   = f_pred + K_gain @ e_t",
    "        P_new   = (np.eye(K_t) - K_gain @ Lam) @ P_pred",
    "",
    "        f[:K_t]       = f_new",
    "        P[:K_t, :K_t] = P_new",
    "",
    "    return -ll",
    "",
    "",
    "# ── Build training window objects ─────────────────────────────────────",
    "train_end = pd.Timestamp('2019-12-31')",
    "train_ret = panel[panel.index <= train_end]",
    "",
    "train_loadings = {k: v for k, v in loadings_result['loadings'].items()",
    "                  if k <= train_end}",
    "train_Kt    = loadings_result['K_t'][loadings_result['K_t'].index <= train_end]",
    "train_lnoise = loadings_result['lambda_noise'][loadings_result['lambda_noise'].index <= train_end]",
    "train_result = {",
    "    **loadings_result,",
    "    'loadings':     train_loadings,",
    "    'K_t':          train_Kt,",
    "    'lambda_noise': train_lnoise,",
    "}",
    "",
    "x0 = np.zeros(K_max)   # log(q)=0 -> q=1",
    "",
    "print(f'Training window: {train_ret.index[0].date()} to {train_ret.index[-1].date()}')",
    "print(f'Training obs:    {len(train_ret)}')",
    "print(f'K_max:           {K_max}')",
    "print('Running MLE... (should complete in <60s)')",
    "",
    "opt_result = optimize.minimize(",
    "    kalman_log_likelihood,",
    "    x0,",
    "    args=(train_ret, train_result, K_max),",
    "    method='L-BFGS-B',",
    "    options={'maxiter': 500, 'ftol': 1e-9, 'disp': False},",
    ")",
    "",
    "Q_hat = np.diag(np.exp(opt_result.x))",
    "",
    "print(f'Convergence:          {opt_result.success}')",
    "print(f'Final log-likelihood: {-opt_result.fun:.2f}')",
    "print(f'Q diagonal (state noise per factor):')",
    "mean_lnoise_train = float(train_result['lambda_noise'].mean())",
    "for k in range(K_max):",
    "    q_k = Q_hat[k, k]",
    "    hl  = 0.5 / q_k if q_k > 1e-12 else float('inf')",
    "    snr = q_k / mean_lnoise_train if mean_lnoise_train > 0 else float('nan')",
    "    print(f'  F{k+1}: q={q_k:.6f}  half-life≈{hl:.1f}d  SNR={snr:.4f}')",
    "print(f'Mean MP noise floor (training): {mean_lnoise_train:.6f}')",
),

md("## Cell 4 — Full-sample Kalman filter"),

# ── Cell 4 ─────────────────────────────────────────────────────────────────
code(
    "def run_kalman_dfm(",
    "    returns: pd.DataFrame,",
    "    loadings_result: dict,",
    "    Q_hat: np.ndarray,",
    ") -> dict:",
    "    \"\"\"",
    "    Run Kalman DFM on full sample with MLE-calibrated Q.",
    "",
    "    Returns dict with:",
    "      f_filtered, f_predicted, innovation, innovation_norm,",
    "      mahal_innov, kalman_gain_norm, implied_vol, factor_contrib,",
    "      K_t_used, lambda_noise_t",
    "    \"\"\"",
    "    K_max = Q_hat.shape[0]",
    "    A     = np.eye(K_max)",
    "    N_obs = returns.shape[1]",
    "",
    "    f   = np.zeros(K_max)",
    "    P   = np.eye(K_max)",
    "",
    "    f_filt_rows   = {}",
    "    f_pred_rows   = {}",
    "    P_diag_rows   = {}",
    "    innov_rows    = {}",
    "    inorm_rows    = {}",
    "    mahal_rows    = {}",
    "    kgain_rows    = {}",
    "    ivol_rows     = {}",
    "    fcontrib_rows = {}",
    "    K_used_rows   = {}",
    "    lnoise_rows   = {}",
    "",
    "    fcols    = [f'F{k+1}' for k in range(K_max)]",
    "    acols    = list(returns.columns)",
    "    dates    = sorted(loadings_result['loadings'].keys())",
    "",
    "    for t_date in dates:",
    "        if t_date not in returns.index:",
    "            continue",
    "        r_t = returns.loc[t_date].values",
    "        has_nan = np.any(np.isnan(r_t))",
    "",
    "        Lambda_t = loadings_result['loadings'][t_date]   # N x K_max",
    "        K_t      = int(loadings_result['K_t'].loc[t_date])",
    "        Lam      = Lambda_t[:, :K_t]                      # N x K_t",
    "        f_k      = f[:K_t]",
    "        P_k      = P[:K_t, :K_t]",
    "        Q_k      = Q_hat[:K_t, :K_t]",
    "        A_k      = A[:K_t, :K_t]",
    "",
    "        lnoise = float(loadings_result['lambda_noise'].loc[t_date])",
    "        H_t    = lnoise * np.eye(N_obs)",
    "",
    "        # Predict",
    "        f_pred_k = A_k @ f_k",
    "        P_pred_k = A_k @ P_k @ A_k.T + Q_k",
    "",
    "        # Store predicted (full K_max vector, zeros for inactive)",
    "        f_pred_full = np.zeros(K_max)",
    "        f_pred_full[:K_t] = f_pred_k",
    "        f_pred_rows[t_date] = f_pred_full",
    "",
    "        # Factor contribution (predicted return from factor model)",
    "        fcontrib_t = Lam @ f_pred_k",
    "        fcontrib_rows[t_date] = fcontrib_t",
    "",
    "        if has_nan:",
    "            # No update — carry forward prediction",
    "            f[:K_t]       = f_pred_k",
    "            P[:K_t, :K_t] = P_pred_k",
    "            f_filt_rows[t_date]   = f_pred_full.copy()",
    "            P_diag_rows[t_date]   = np.diag(P)[:K_max].copy()",
    "            innov_rows[t_date]    = np.zeros(N_obs)",
    "            inorm_rows[t_date]    = np.nan",
    "            mahal_rows[t_date]    = np.nan",
    "            kgain_rows[t_date]    = np.nan",
    "            ivol_rows[t_date]     = np.full(N_obs, np.nan)",
    "            K_used_rows[t_date]   = K_t",
    "            lnoise_rows[t_date]   = lnoise",
    "            continue",
    "",
    "        # Innovation",
    "        e_t = r_t - Lam @ f_pred_k",
    "        S_t = Lam @ P_pred_k @ Lam.T + H_t",
    "",
    "        try:",
    "            S_inv  = np.linalg.solve(S_t, np.eye(N_obs))",
    "            mahal  = float(e_t @ S_inv @ e_t)",
    "        except np.linalg.LinAlgError:",
    "            S_inv  = np.linalg.pinv(S_t)",
    "            mahal  = float(e_t @ S_inv @ e_t)",
    "",
    "        # Update",
    "        K_gain  = P_pred_k @ Lam.T @ S_inv  # K_t x N",
    "        f_new   = f_pred_k + K_gain @ e_t",
    "        P_new   = (np.eye(K_t) - K_gain @ Lam) @ P_pred_k",
    "",
    "        # Symmetrize P to prevent numerical drift",
    "        P_new = 0.5 * (P_new + P_new.T)",
    "",
    "        f[:K_t]       = f_new",
    "        P[:K_t, :K_t] = P_new",
    "",
    "        # Implied covariance: Sigma_t = Lambda P Lambda.T + H",
    "        Sigma_t = Lam @ P_new @ Lam.T + H_t",
    "        ivol_t  = np.sqrt(np.maximum(np.diag(Sigma_t), 0.0))",
    "",
    "        f_filt_full = np.zeros(K_max)",
    "        f_filt_full[:K_t] = f_new",
    "        P_diag_full = np.zeros(K_max)",
    "        P_diag_full[:K_t] = np.diag(P_new)",
    "",
    "        f_filt_rows[t_date]   = f_filt_full",
    "        P_diag_rows[t_date]   = P_diag_full",
    "        innov_rows[t_date]    = e_t",
    "        inorm_rows[t_date]    = float(np.linalg.norm(e_t))",
    "        mahal_rows[t_date]    = mahal",
    "        kgain_rows[t_date]    = float(np.linalg.norm(K_gain, 'fro'))",
    "        ivol_rows[t_date]     = ivol_t",
    "        K_used_rows[t_date]   = K_t",
    "        lnoise_rows[t_date]   = lnoise",
    "",
    "    all_dates = sorted(f_filt_rows.keys())",
    "",
    "    out = {",
    "        'f_filtered':       pd.DataFrame(f_filt_rows,   index=fcols).T.rename_axis('date'),",
    "        'f_predicted':      pd.DataFrame(f_pred_rows,   index=fcols).T.rename_axis('date'),",
    "        'P_diag':           pd.DataFrame(P_diag_rows,   index=fcols).T.rename_axis('date'),",
    "        'innovation':       pd.DataFrame(innov_rows,    index=acols).T.rename_axis('date'),",
    "        'innovation_norm':  pd.Series(inorm_rows,  name='innovation_norm').rename_axis('date'),",
    "        'mahal_innov':      pd.Series(mahal_rows,  name='mahal_innov').rename_axis('date'),",
    "        'kalman_gain_norm': pd.Series(kgain_rows,  name='kg_norm').rename_axis('date'),",
    "        'implied_vol':      pd.DataFrame(ivol_rows,     index=acols).T.rename_axis('date'),",
    "        'factor_contrib':   pd.DataFrame(fcontrib_rows, index=acols).T.rename_axis('date'),",
    "        'K_t_used':         pd.Series(K_used_rows, name='K_t').rename_axis('date'),",
    "        'lambda_noise_t':   pd.Series(lnoise_rows, name='lambda_noise').rename_axis('date'),",
    "    }",
    "    return out",
    "",
    "",
    "# ── Run full-sample filter ────────────────────────────────────────────",
    "print('Running full-sample Kalman filter...')",
    "dfm = run_kalman_dfm(panel, loadings_result, Q_hat)",
    "",
    "for k, v in dfm.items():",
    "    if hasattr(v, 'shape'):",
    "        print(f'  {k:22s}: {v.shape}')",
    "    elif hasattr(v, '__len__'):",
    "        print(f'  {k:22s}: ({len(v)},)')",
    "",
    "last_date = dfm['f_filtered'].dropna(how='all').index[-1]",
    "lf = dfm['f_filtered'].loc[last_date]",
    "print(f'\\nLatest date: {last_date.date()}')",
    "print('Latest filtered factors: ' +",
    "      '  '.join(f'F{k+1}={lf[f\"F{k+1}\"]:.4f}' for k in range(K_max)))",
    "print(f'Latest innovation norm:    {dfm[\"innovation_norm\"].dropna().iloc[-1]:.4f}')",
    "last_mahal = dfm['mahal_innov'].dropna().iloc[-1]",
    "chi2_95    = sp_stats.chi2.ppf(0.95, df=N)",
    "print(f'Latest Mahal innovation:   {last_mahal:.2f}  (chi2({N}) 95th pctile = {chi2_95:.2f})')",
),

md("## Cell 5 — Factor interpretability analysis"),

# ── Cell 5 ─────────────────────────────────────────────────────────────────
code(
    "# ── Helpers ──────────────────────────────────────────────────────────",
    "def add_regime_vrects(fig, regime_ser, row=None, col=None):",
    "    REGIME_HEX = {'Calm':'#2ecc71','Elevated':'#f39c12','Turbulent':'#e67e22','Crisis':'#e74c3c'}",
    "    in_block, x0, prev_r = False, None, None",
    "    kw = dict(fillcolor=None, opacity=0.12, line_width=0)",
    "    if row is not None:",
    "        kw.update(row=row, col=col)",
    "    for dt, r in regime_ser.items():",
    "        if r != prev_r:",
    "            if in_block and prev_r in REGIME_HEX:",
    "                kw['fillcolor'] = REGIME_HEX[prev_r]",
    "                if row is not None:",
    "                    fig.add_vrect(x0=x0, x1=dt, **kw)",
    "                else:",
    "                    fig.add_vrect(x0=x0, x1=dt, fillcolor=REGIME_HEX[prev_r], opacity=0.12, line_width=0)",
    "            x0, in_block = dt, True",
    "        prev_r = r",
    "    if in_block and prev_r in REGIME_HEX:",
    "        if row is not None:",
    "            fig.add_vrect(x0=x0, x1=regime_ser.index[-1], fillcolor=REGIME_HEX[prev_r], opacity=0.12, line_width=0, row=row, col=col)",
    "        else:",
    "            fig.add_vrect(x0=x0, x1=regime_ser.index[-1], fillcolor=REGIME_HEX[prev_r], opacity=0.12, line_width=0)",
    "",
    "# ── Plot A: K_t + factor scores ──────────────────────────────────────",
    "f_filt = dfm['f_filtered']",
    "f_pred = dfm['f_predicted']",
    "P_diag = dfm['P_diag']",
    "reg_ser = turb.regime.reindex(f_filt.index, method='ffill')",
    "",
    "fig_A = make_subplots(rows=4, cols=1, shared_xaxes=True,",
    "    row_heights=[0.2, 0.27, 0.27, 0.27], vertical_spacing=0.03,",
    "    subplot_titles=['K_t (signal factors)', 'F1 filtered', 'F2 filtered', 'F3 filtered'])",
    "",
    "# Regime vrects on all rows",
    "for row_i in range(1, 5):",
    "    in_block, x0, prev_r = False, None, None",
    "    for dt, r in reg_ser.items():",
    "        REGIME_HEX = {'Calm':'#2ecc71','Elevated':'#f39c12','Turbulent':'#e67e22','Crisis':'#e74c3c'}",
    "        if r != prev_r:",
    "            if in_block and prev_r in REGIME_HEX:",
    "                fig_A.add_vrect(x0=x0, x1=dt, fillcolor=REGIME_HEX[prev_r], opacity=0.10, line_width=0, row=row_i, col=1)",
    "            x0, in_block = dt, True",
    "        prev_r = r",
    "    if in_block and prev_r in REGIME_HEX:",
    "        fig_A.add_vrect(x0=x0, x1=reg_ser.index[-1], fillcolor=REGIME_HEX[prev_r], opacity=0.10, line_width=0, row=row_i, col=1)",
    "",
    "# Row 1: K_t",
    "fig_A.add_trace(go.Scatter(x=dfm['K_t_used'].index, y=dfm['K_t_used'].values,",
    "    mode='lines', name='K_t', line=dict(color='#00d4aa', width=1.2, shape='hv')), row=1, col=1)",
    "",
    "# Rows 2-4: F1, F2, F3",
    "factor_colors = ['#e74c3c', '#3498db', '#9b59b6']",
    "factor_rgba   = ['rgba(231,76,60,0.12)', 'rgba(52,152,219,0.12)', 'rgba(155,89,182,0.12)']",
    "for k in range(3):",
    "    fk    = f'F{k+1}'",
    "    ff    = f_filt[fk].dropna()",
    "    fp    = f_pred[fk].reindex(ff.index)",
    "    pd_   = P_diag[fk].reindex(ff.index)",
    "    band  = 1.96 * np.sqrt(pd_.clip(lower=0))",
    "    row_i = k + 2",
    "    clr   = factor_colors[k]",
    "    clr_fill = factor_rgba[k]",
    "    # posterior uncertainty band",
    "    fig_A.add_trace(go.Scatter(",
    "        x=list(ff.index) + list(ff.index[::-1]),",
    "        y=list((ff + band).values) + list((ff - band).values[::-1]),",
    "        fill='toself', fillcolor=clr_fill,",
    "        line=dict(width=0), showlegend=False, name=f'{fk} 95% band'),",
    "        row=row_i, col=1)",
    "    fig_A.add_trace(go.Scatter(x=fp.index, y=fp.values, mode='lines',",
    "        name=f'{fk} pred', line=dict(color=clr, width=0.8, dash='dot')), row=row_i, col=1)",
    "    fig_A.add_trace(go.Scatter(x=ff.index, y=ff.values, mode='lines',",
    "        name=f'{fk} filtered', line=dict(color=clr, width=1.3)), row=row_i, col=1)",
    "",
    "fig_A.update_layout(template='plotly_dark', height=700,",
    "    title='DFM: Dynamic K and Kalman-filtered factor scores',",
    "    margin=dict(l=50, r=40, t=60, b=60),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117',",
    "    legend=dict(font=dict(size=9)))",
    "fig_A.show()",
    "",
    "# ── Plot B: Factor loading evolution ─────────────────────────────────",
    "# Mean absolute loading over time per asset per factor",
    "loading_ts = {f'F{k+1}': {} for k in range(3)}",
    "for dt, Lam in loadings_result['loadings'].items():",
    "    for k in range(3):",
    "        loading_ts[f'F{k+1}'][dt] = Lam[:, k]",
    "",
    "asset_names = loadings_result['asset_names']",
    "mean_abs_load = {}",
    "for fk, ts in loading_ts.items():",
    "    arr_  = np.array(list(ts.values()))  # T x N",
    "    mean_abs_load[fk] = np.mean(np.abs(arr_), axis=0)",
    "",
    "fig_B = make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing=0.04,",
    "    subplot_titles=['F1 — top-3 asset loadings', 'F2 — top-3 asset loadings', 'F3 — top-3 asset loadings'])",
    "top_colors = ['#e74c3c', '#3498db', '#9b59b6']",
    "line_colors = ['#f39c12', '#2ecc71', '#00d4aa', '#e74c3c', '#3498db']",
    "for ki, fk in enumerate(['F1','F2','F3']):",
    "    top3_idx = np.argsort(mean_abs_load[fk])[::-1][:3]",
    "    top3_assets = [asset_names[i] for i in top3_idx]",
    "    ts_arr = loading_ts[fk]",
    "    dates_ = sorted(ts_arr.keys())",
    "    for j, (asset_i, asset_n) in enumerate(zip(top3_idx, top3_assets)):",
    "        vals_ = [np.abs(ts_arr[d][asset_i]) for d in dates_]",
    "        fig_B.add_trace(go.Scatter(x=dates_, y=vals_, mode='lines',",
    "            name=f'{fk}/{asset_n}', line=dict(color=line_colors[j], width=1.2)),",
    "            row=ki+1, col=1)",
    "",
    "fig_B.update_layout(template='plotly_dark', height=550,",
    "    title='Factor loading evolution: top 3 assets per factor',",
    "    margin=dict(l=50,r=40,t=60,b=60),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_B.show()",
    "",
    "# ── Plot C: Innovation diagnostics ───────────────────────────────────",
    "inorm = dfm['innovation_norm'].dropna()",
    "mahal = dfm['mahal_innov'].dropna()",
    "inorm_thr = inorm.mean() + 2 * inorm.std()",
    "chi2_95   = sp_stats.chi2.ppf(0.95, df=N)",
    "",
    "fig_C = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.05,",
    "    subplot_titles=['Innovation norm ||e_t||', 'Mahalanobis chi2 statistic'])",
    "",
    "# Top panel",
    "fig_C.add_trace(go.Scatter(x=inorm.index, y=inorm.values, mode='lines',",
    "    name='||e_t||', line=dict(color='#3498db', width=0.9)), row=1, col=1)",
    "above_inorm = inorm[inorm > inorm_thr]",
    "fig_C.add_trace(go.Scatter(x=above_inorm.index, y=above_inorm.values, mode='markers',",
    "    marker=dict(color='#e74c3c', size=4), name='above 2σ'), row=1, col=1)",
    "fig_C.add_hline(y=inorm_thr, line_dash='dash', line_color='#f39c12', line_width=1, row=1, col=1)",
    "",
    "# Bottom panel",
    "fig_C.add_trace(go.Scatter(x=mahal.index, y=mahal.values, mode='lines',",
    "    name='Mahal', line=dict(color='#9b59b6', width=0.9)), row=2, col=1)",
    "above_chi2 = mahal[mahal > chi2_95]",
    "fig_C.add_trace(go.Scatter(x=above_chi2.index, y=above_chi2.values, mode='markers',",
    "    marker=dict(color='#e74c3c', size=4), name=f'>chi2_95'), row=2, col=1)",
    "fig_C.add_hline(y=chi2_95, line_dash='dash', line_color='#f39c12', line_width=1, row=2, col=1)",
    "",
    "# Annotate 5 largest spikes in inorm",
    "top5_inorm = inorm.nlargest(5)",
    "for dt_, val_ in top5_inorm.items():",
    "    fig_C.add_annotation(x=dt_, y=val_, text=str(dt_.date()),",
    "        font=dict(size=8, color='#e74c3c'), showarrow=True, arrowwidth=0.5,",
    "        arrowcolor='#e74c3c', ax=0, ay=-20, row=1, col=1)",
    "",
    "fig_C.update_layout(template='plotly_dark', height=480,",
    "    title='Kalman filter innovations: structural break detection',",
    "    margin=dict(l=50,r=40,t=60,b=70),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_C.add_annotation(",
    "    x=0.01, y=-0.12, xref='paper', yref='paper', showarrow=False,",
    "    text='Innovation norm = ||r_t − Λ f_{t|t-1}||. Spikes = factor model failed to predict return. Chi2 stat has known null under H0.',",
    "    font=dict(size=9, color='#aaaaaa'))",
    "fig_C.show()",
    "",
    "# ── Plot D: Implied vol vs realized ──────────────────────────────────",
    "fx_assets = list(fx.columns)[:5]   # CLP, BRL, MXN, COP, PEN",
    "ivol_df = dfm['implied_vol']",
    "fig_D = make_subplots(rows=5, cols=1, shared_xaxes=True, vertical_spacing=0.03,",
    "    subplot_titles=fx_assets)",
    "rvol_colors = ['#e74c3c','#3498db','#2ecc71','#f39c12','#9b59b6']",
    "for i, asset in enumerate(fx_assets):",
    "    if asset not in ivol_df.columns:",
    "        continue",
    "    iv = ivol_df[asset].dropna() * np.sqrt(252)",
    "    rv = panel[asset].rolling(21, min_periods=10).std().dropna() * np.sqrt(252)",
    "    fig_D.add_trace(go.Scatter(x=iv.index, y=iv.values, mode='lines',",
    "        name=f'{asset} DFM', line=dict(color=rvol_colors[i], width=1.2)),",
    "        row=i+1, col=1)",
    "    fig_D.add_trace(go.Scatter(x=rv.index, y=rv.values, mode='lines',",
    "        name=f'{asset} realized', line=dict(color=rvol_colors[i], width=0.8, dash='dot')),",
    "        row=i+1, col=1)",
    "fig_D.update_layout(template='plotly_dark', height=750,",
    "    title='DFM implied vs realized volatility: FX assets',",
    "    margin=dict(l=50,r=40,t=60,b=70),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_D.add_annotation(",
    "    x=0.01, y=-0.06, xref='paper', yref='paper', showarrow=False,",
    "    text='DFM implied vol from Σ_t = Λ P Λᵀ + H. Realized = 21d rolling std annualized.',",
    "    font=dict(size=9, color='#aaaaaa'))",
    "fig_D.show()",
    "",
    "# ── Plot E: Return decomposition ─────────────────────────────────────",
    "selected_assets = ['BRL', 'CLP', 'BRA']",
    "fc_df   = dfm['factor_contrib']",
    "fig_E = make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing=0.04,",
    "    subplot_titles=[f'{a}: systematic vs idiosyncratic (monthly)' for a in selected_assets])",
    "bar_colors = ['#3498db', '#e74c3c', '#2ecc71']",
    "for i, asset in enumerate(selected_assets):",
    "    if asset not in panel.columns or asset not in fc_df.columns:",
    "        print(f'  skip {asset}: not in panel or factor_contrib')",
    "        continue",
    "    r_m   = panel[asset].resample('ME').sum()",
    "    fc_m  = fc_df[asset].resample('ME').sum()",
    "    idio_m = r_m - fc_m",
    "    idx_m = r_m.index",
    "    fig_E.add_trace(go.Bar(x=idx_m, y=fc_m.values, name=f'{asset} systematic',",
    "        marker_color=bar_colors[i], opacity=0.85), row=i+1, col=1)",
    "    fig_E.add_trace(go.Bar(x=idx_m, y=idio_m.values, name=f'{asset} idiosyncratic',",
    "        marker_color=bar_colors[i], opacity=0.35), row=i+1, col=1)",
    "fig_E.update_layout(template='plotly_dark', height=560, barmode='relative',",
    "    title='Return decomposition: systematic vs idiosyncratic',",
    "    margin=dict(l=50,r=40,t=60,b=70),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_E.add_annotation(",
    "    x=0.01, y=-0.07, xref='paper', yref='paper', showarrow=False,",
    "    text='Systematic = Λ f_{t|t-1}. Idiosyncratic = residual unexplained by factor model.',",
    "    font=dict(size=9, color='#aaaaaa'))",
    "fig_E.show()",
),

md("## Cell 6 — Empirical validation"),

# ── Cell 6 ─────────────────────────────────────────────────────────────────
code(
    "from scipy.stats import ks_2samp",
    "",
    "# ── Test 1: Cross-correlation mahal_innov vs tau ──────────────────────",
    "tau_ser   = turb.turbulence.dropna()",
    "mahal_ser = dfm['mahal_innov'].dropna()",
    "common    = tau_ser.index.intersection(mahal_ser.index)",
    "tau_c     = tau_ser.reindex(common)",
    "mah_c     = mahal_ser.reindex(common)",
    "",
    "lags   = range(-15, 16)",
    "xcorr  = []",
    "for lag in lags:",
    "    if lag < 0:",
    "        corr_ = tau_c.iloc[-lag:].values, mah_c.iloc[:lag].values",
    "    elif lag > 0:",
    "        corr_ = tau_c.iloc[:-lag].values, mah_c.iloc[lag:].values",
    "    else:",
    "        corr_ = tau_c.values, mah_c.values",
    "    if len(corr_[0]) > 10:",
    "        xcorr.append(np.corrcoef(corr_[0], corr_[1])[0, 1])",
    "    else:",
    "        xcorr.append(np.nan)",
    "",
    "xcorr = np.array(xcorr)",
    "best_lag = list(lags)[int(np.nanargmax(xcorr))]",
    "best_r   = xcorr[int(np.nanargmax(xcorr))]",
    "",
    "fig_xcorr = go.Figure()",
    "fig_xcorr.add_bar(x=list(lags), y=xcorr.tolist(),",
    "    marker_color=['#e74c3c' if l < 0 else '#3498db' for l in lags])",
    "fig_xcorr.add_vline(x=0, line_dash='dash', line_color='#ffffff', line_width=0.8)",
    "fig_xcorr.update_layout(template='plotly_dark', height=300,",
    "    title='Cross-correlation: DFM Mahal innovation vs turbulence tau',",
    "    xaxis_title='Lag (days; negative = innovation leads tau)',",
    "    yaxis_title='Pearson correlation',",
    "    margin=dict(l=50,r=40,t=50,b=50),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_xcorr.show()",
    "",
    "print(f'Peak cross-correlation: r={best_r:.3f} at lag={best_lag} days')",
    "if best_lag < 0:",
    "    print(f'DFM innovation LEADS turbulence by {-best_lag} days')",
    "elif best_lag > 0:",
    "    print(f'DFM innovation LAGS turbulence by {best_lag} days')",
    "else:",
    "    print('DFM innovation is contemporaneous with turbulence')",
    "",
    "# ── Test 2: Prediction accuracy by regime ─────────────────────────────",
    "f_filt = dfm['f_filtered']",
    "reg_ser = turb.regime.reindex(f_filt.dropna(how='all').index, method='ffill')",
    "f_filt_c = f_filt.loc[reg_ser.index]",
    "",
    "print('\\nPrediction RMSE by turbulence regime:')",
    "print(f'  {\"Regime\":<12} {\"N_obs\":>6}' + ''.join(f'  {\"F\"+str(k+1)+\" RMSE\":>8}' for k in range(3)) + '  vs Naive')",
    "for regime in ['Calm','Elevated','Turbulent','Crisis']:",
    "    mask = reg_ser == regime",
    "    if mask.sum() < 10:",
    "        continue",
    "    sub = f_filt_c.loc[mask]",
    "    # one-step diff as proxy for prediction error (random walk: pred = prev)",
    "    diffs = sub.diff().dropna()",
    "    rmse_per_f = [float(np.sqrt((diffs[f'F{k+1}']**2).mean())) for k in range(3)]",
    "    naive = [float(sub[f'F{k+1}'].std()) for k in range(3)]",
    "    vs_naive = np.mean([rmse_per_f[k]/naive[k] if naive[k]>0 else np.nan for k in range(3)])",
    "    print(f'  {regime:<12} {mask.sum():>6}' +",
    "          ''.join(f'  {rmse_per_f[k]:>8.4f}' for k in range(3)) +",
    "          f'  {vs_naive:.3f}')",
    "",
    "# ── Test 3: MP noise eigenvalue distribution ──────────────────────────",
    "calm_dates = turb.regime[turb.regime == 'Calm'].index",
    "noise_eigs_calm = []",
    "arr_panel = panel.values",
    "dates_panel = panel.index",
    "",
    "print('\\nCollecting noise eigenvalues for calm periods...')",
    "for i, dt in enumerate(dates_panel):",
    "    if dt not in calm_dates:",
    "        continue",
    "    if i < 251:",
    "        continue",
    "    win = arr_panel[i-251:i+1]",
    "    win_c = win.copy()",
    "    for c in range(win_c.shape[1]):",
    "        m = np.isnan(win_c[:, c])",
    "        win_c[m, c] = np.nanmean(win_c[:, c])",
    "    cov_ = np.cov(win_c, rowvar=False)",
    "    ev_, _ = np.linalg.eigh(cov_)",
    "    ev_ = np.sort(ev_)[::-1]",
    "    lp_, _, K_ = marchenko_pastur_threshold(ev_, N, 252)",
    "    # sub-threshold eigenvalues",
    "    noise_eigs_calm.extend(ev_[K_:].tolist())",
    "",
    "noise_arr = np.array(noise_eigs_calm)",
    "noise_arr = noise_arr[noise_arr > 0]",
    "",
    "# MP theoretical density (vectorized)",
    "gamma0 = N / 252",
    "sigma2_0 = np.median(noise_arr)",
    "lp0 = sigma2_0 * (1 + np.sqrt(gamma0))**2",
    "lm0 = sigma2_0 * (1 - np.sqrt(gamma0))**2",
    "x_mp = np.linspace(max(lm0*0.01, 1e-8), lp0, 300)",
    "mp_dens = (np.sqrt(np.maximum((lp0 - x_mp) * (x_mp - lm0), 0.0))",
    "           / (2 * np.pi * gamma0 * sigma2_0 * np.maximum(x_mp, 1e-10)))",
    "mp_dens_norm = mp_dens / (mp_dens.sum() * (x_mp[1] - x_mp[0]))",
    "",
    "# Clip noise_arr to [lm0, lp0] for KS test",
    "noise_clipped = noise_arr[(noise_arr >= lm0) & (noise_arr <= lp0)]",
    "",
    "fig_mp = go.Figure()",
    "fig_mp.add_trace(go.Histogram(x=noise_clipped.tolist(), nbinsx=50,",
    "    histnorm='probability density', name='Empirical (calm)', opacity=0.6,",
    "    marker_color='#3498db'))",
    "fig_mp.add_trace(go.Scatter(x=x_mp.tolist(), y=mp_dens_norm.tolist(),",
    "    mode='lines', name='MP theoretical', line=dict(color='#e74c3c', width=2)))",
    "fig_mp.update_layout(template='plotly_dark', height=320,",
    "    title='Noise eigenvalue distribution vs Marchenko-Pastur (calm periods)',",
    "    xaxis_title='Eigenvalue', yaxis_title='Density',",
    "    margin=dict(l=50,r=40,t=50,b=60),",
    "    plot_bgcolor='#0d1117', paper_bgcolor='#0d1117')",
    "fig_mp.show()",
    "",
    "# KS test: compare empirical to uniform on [lm0, lp0] as proxy",
    "if len(noise_clipped) > 50:",
    "    ks_stat, ks_p = ks_2samp(noise_clipped,",
    "        np.random.default_rng(42).uniform(lm0, lp0, len(noise_clipped)))",
    "    print(f'KS test p-value: {ks_p:.3f}')",
    "    print('(p > 0.05 = cannot reject MP null for noise eigenvalues)')",
    "else:",
    "    print('Not enough calm-period noise eigenvalues for KS test.')",
    "",
    "# ── Test 4: K_t as leading stress indicator ───────────────────────────",
    "Kt_ser  = dfm['K_t_used'].dropna()",
    "tau_c2  = turb.turbulence.reindex(Kt_ser.index, method='ffill').dropna()",
    "Kt_c2   = Kt_ser.reindex(tau_c2.index)",
    "",
    "lags4  = range(-15, 16)",
    "xcorr4 = []",
    "for lag in lags4:",
    "    if lag < 0:",
    "        c1, c2 = tau_c2.iloc[-lag:].values, Kt_c2.iloc[:lag].values",
    "    elif lag > 0:",
    "        c1, c2 = tau_c2.iloc[:-lag].values, Kt_c2.iloc[lag:].values",
    "    else:",
    "        c1, c2 = tau_c2.values, Kt_c2.values",
    "    if len(c1) > 10:",
    "        xcorr4.append(np.corrcoef(c1, c2)[0, 1])",
    "    else:",
    "        xcorr4.append(np.nan)",
    "",
    "xcorr4   = np.array(xcorr4)",
    "best_lag4 = list(lags4)[int(np.nanargmax(np.abs(xcorr4)))]",
    "best_r4   = xcorr4[int(np.nanargmax(np.abs(xcorr4)))]",
    "print(f'\\nPeak cross-correlation of K_t with tau: r={best_r4:.3f} at lag={best_lag4} days')",
    "if best_lag4 < 0:",
    "    print(f'K_t LEADS turbulence by {-best_lag4} days (genuine early warning)')",
    "elif best_lag4 > 0:",
    "    print(f'K_t LAGS turbulence by {best_lag4} days (reactive)')",
    "else:",
    "    print('K_t is contemporaneous with turbulence')",
),

md("## Cell 7 — Factor interpretation narrative"),

# ── Cell 7 ─────────────────────────────────────────────────────────────────
code(
    "ev_df   = loadings_result['explained_var']",
    "f_filt  = dfm['f_filtered']",
    "Kt_ser  = dfm['K_t_used'].dropna()",
    "",
    "# Period windows",
    "periods = {",
    "    'normal_2018': ('2018-01-01', '2018-12-31'),",
    "    'covid':       ('2020-02-20', '2020-04-30'),",
    "    'estallido':   ('2019-10-01', '2019-11-30'),",
    "}",
    "",
    "print('=' * 60)",
    "print('DYNAMIC FACTOR MODEL: FACTOR INTERPRETATION')",
    "print('=' * 60)",
    "",
    "for k in range(K_max):",
    "    fk = f'F{k+1}'",
    "    mean_ev = float(ev_df[fk].mean()) if fk in ev_df.columns else float('nan')",
    "",
    "    # Top loading assets (mean absolute loading)",
    "    mean_abs = {}",
    "    for dt, Lam in loadings_result['loadings'].items():",
    "        if k < Lam.shape[1]:",
    "            for j, an in enumerate(loadings_result['asset_names']):",
    "                mean_abs[an] = mean_abs.get(an, []) + [abs(Lam[j, k])]",
    "    top3 = sorted(mean_abs, key=lambda x: np.mean(mean_abs[x]), reverse=True)[:3]",
    "",
    "    print(f'\\nF{k+1} — mean explained variance: {mean_ev:.1%}')",
    "    print(f'  Top loading assets: {top3}')",
    "    for pname, (ps, pe) in periods.items():",
    "        ts_ = pd.Timestamp(ps)",
    "        te_ = pd.Timestamp(pe)",
    "        sub = f_filt.loc[(f_filt.index >= ts_) & (f_filt.index <= te_), fk]",
    "        val = float(sub.mean()) if len(sub) > 0 else float('nan')",
    "        print(f'  Mean score, {pname:15s}: {val:.4f}')",
    "    print(f'  Interpretation: [fill manually after inspection]')",
    "",
    "print()",
    "print('SIGNAL PROPERTIES:')",
    "print(f'  Mean K_t: {Kt_ser.mean():.2f} factors')",
    "",
    "for pname, (ps, pe) in periods.items():",
    "    ts_ = pd.Timestamp(ps)",
    "    te_ = pd.Timestamp(pe)",
    "    sub = Kt_ser.loc[(Kt_ser.index >= ts_) & (Kt_ser.index <= te_)]",
    "    if len(sub) > 0:",
    "        print(f'  K_t during {pname}: mean={sub.mean():.2f}  peak={int(sub.max())}')",
    "",
    "print(f'  Innovation lead over tau: {best_lag} days  (negative = leads)')",
    "",
    "# Calm vs Crisis RMSE ratio",
    "reg_ser2 = turb.regime.reindex(f_filt.dropna(how='all').index, method='ffill')",
    "f_filt_c2 = f_filt.loc[reg_ser2.index]",
    "rmse_by_regime = {}",
    "for regime in ['Calm', 'Crisis']:",
    "    mask = reg_ser2 == regime",
    "    if mask.sum() < 5:",
    "        rmse_by_regime[regime] = float('nan')",
    "        continue",
    "    sub = f_filt_c2.loc[mask]",
    "    diffs = sub.diff().dropna()",
    "    rmse_by_regime[regime] = float(np.sqrt((diffs[['F1','F2','F3']]**2).mean().mean()))",
    "if rmse_by_regime.get('Calm', 0) and rmse_by_regime.get('Crisis', 0):",
    "    ratio = rmse_by_regime['Crisis'] / rmse_by_regime['Calm']",
    "    print(f'  Calm RMSE / Crisis RMSE ratio: {1/ratio:.2f}  (Crisis {ratio:.2f}x higher)')",
),

md("## Cell 8 — Save results"),

# ── Cell 8 ─────────────────────────────────────────────────────────────────
code(
    "import pickle",
    "",
    "# ── Save MLE params ──────────────────────────────────────────────────",
    "os.makedirs('../data/_cache', exist_ok=True)",
    "params_out = {",
    "    'Q_hat':          Q_hat,",
    "    'K_max':          K_max,",
    "    'N':              N,",
    "    'window':         252,",
    "    'lam_smooth':     0.97,",
    "    'K_min':          2,",
    "    'K_max_bound':    5,",
    "    'convergence':    bool(opt_result.success),",
    "    'log_likelihood': float(-opt_result.fun),",
    "    'trained_on':     '2015-2019',",
    "    'asset_names':    list(panel.columns),",
    "}",
    "with open('../data/_cache/dfm_params.pkl', 'wb') as fh:",
    "    pickle.dump(params_out, fh)",
    "print('Saved: data/_cache/dfm_params.pkl')",
    "",
    "# ── Export to Excel ───────────────────────────────────────────────────",
    "os.makedirs('../exports', exist_ok=True)",
    "fname = f'../exports/dfm_results_{date.today()}.xlsx'",
    "with pd.ExcelWriter(fname, engine='openpyxl') as writer:",
    "    dfm['f_filtered'].to_excel(writer,       sheet_name='Filtered Factors')",
    "    dfm['f_predicted'].to_excel(writer,      sheet_name='Predicted Factors')",
    "    dfm['innovation'].to_excel(writer,        sheet_name='Innovations')",
    "    pd.DataFrame({",
    "        'innovation_norm':  dfm['innovation_norm'],",
    "        'mahal_innov':      dfm['mahal_innov'],",
    "        'kalman_gain_norm': dfm['kalman_gain_norm'],",
    "    }).to_excel(writer, sheet_name='Innovation Diagnostics')",
    "    pd.DataFrame({",
    "        'K_t':          dfm['K_t_used'],",
    "        'lambda_noise': dfm['lambda_noise_t'],",
    "    }).to_excel(writer, sheet_name='MP Diagnostics')",
    "    dfm['implied_vol'].to_excel(writer,       sheet_name='Implied Vol')",
    "    dfm['factor_contrib'].to_excel(writer,    sheet_name='Factor Contribution')",
    "    loadings_result['explained_var'].to_excel(writer, sheet_name='Explained Variance')",
    "    last_key = max(loadings_result['loadings'].keys())",
    "    pd.DataFrame(",
    "        loadings_result['loadings'][last_key],",
    "        index=list(panel.columns),",
    "        columns=[f'F{k+1}' for k in range(K_max)],",
    "    ).to_excel(writer, sheet_name='Latest Loadings')",
    "    pd.DataFrame({",
    "        'factor': [f'F{k+1}' for k in range(K_max)],",
    "        'Q_diagonal': np.diag(Q_hat),",
    "    }).to_excel(writer, sheet_name='MLE Parameters')",
    "print(f'Saved: {fname}')",
),

])

print("Done.")
